add lib:echo and use it to replace log/log2

diff --git a/misc/dropbatch b/misc/dropbatch
--- a/misc/dropbatch
+++ b/misc/dropbatch
@@ -25,7 +25,7 @@ done; shift $((OPTIND-1))
 host=${1%%.*}
 script=$2
 
-[[ $host ]] || die "missing hostname parameter"
+[[ $host ]] || die "Missing hostname parameter"
 
 if (( usenfs )); then
 	targetdir=/n/$host/Dropbox
@@ -46,15 +46,15 @@ if [[ ! $script || $script == "-" ]]; then
 		cat > "$tmp"
 	fi
 	if ! grep -vqs "^#!" "$tmp"; then
-		notice "script is empty, exiting"
+		notice "Script is empty, exiting"
 		rm -f "$tmp"
 		exit
 	fi
 	script=$tmp
 elif [[ ! -f $script ]]; then
-	die "script file '$script' not found"
+	die "Script file '$script' not found"
 elif [[ ! -s $script ]]; then
-	notice "script is empty, ignoring"
+	warn "Script is empty, ignoring"
 	exit
 fi
 
@@ -65,10 +65,10 @@ chmod u+x "$dest.tmp" &&
 mv "$dest.tmp" "$dest" &&
 rm "$script" || exit
 
-log "job $dest submitted"
+lib:echo "Job $dest submitted"
 
 if (( wait )); then
-	log "waiting for job to be processed..."
+	lib:echo "Waiting for job to be processed..."
 	time=0
 	if (( usenfs )); then
 		# For submissions over NFS, wait for the job to complete before
@@ -77,14 +77,14 @@ if (( wait )); then
 		time=3; sleep $time
 	fi
 	until [[ -e $dest.done ]]; do
-		printf '\rwaiting (%ds)...' $[time++]
+		printf '\rWaiting (%ds)...' $[time++]
 		sleep 1
 	done
 	printf '\n'
 	if [[ -e $dest.log ]]; then
-		log "job finished"
+		lib:echo "Job finished"
 	else
-		log "job finished, waiting for result..."
+		lib:echo "Job finished, waiting for result..."
 		time=0
 		until [[ -e $dest.log ]]; do
 			if [[ -t 1 ]]; then
diff --git a/net/vitables b/net/vitables
--- a/net/vitables
+++ b/net/vitables
@@ -20,15 +20,15 @@ cp "$temp" "$orig"
 while true; do
 	${EDITOR:-vi} "$temp"
 	if ! grep -qs '^[^#]' "$temp"; then
-		log "file empty, reload aborted"
+		lib:echo "File empty, reload aborted" >&2
 		break
 	elif cmp -s "$temp" "$orig"; then
-		log "no changes made"
+		lib:echo "No changes made" >&2
 		break
 	elif sudo $iptables-restore < "$temp"; then
-		log "rules reloaded successfully"
+		lib:echo "Rules reloaded successfully"
 		break
-	elif ! confirm "error: failed to load rules; edit again?"; then
+	elif ! confirm "error: Failed to load rules; edit again?"; then
 		r=1
 		break
 	fi
