settitle: clean up

diff --git a/misc/settitle b/misc/settitle
--- a/misc/settitle
+++ b/misc/settitle
@@ -2,58 +2,66 @@
 # settitle -- update the terminal window titlebar or window name
 
 usage() {
-	echo "Usage: ${0##*/} [-ersw] <title>"
+	echo "Usage: ${0##*/} [-arsw] <title>"
 	echo ""
 	echo "Update the terminal's window titlebar."
 	echo ""
 	echo "Options:"
-	echo "  -e            output escaped sequence"
+	echo "  -a            use nonstandard BEL terminator instead of ST"
 	echo "  -r            ask terminal to restore saved title"
 	echo "  -s            ask terminal to save current title"
 	echo "  -w            set tmux/screen \"window name\""
 }
 
-ESC='\e' ST='\e\\' BEL='\007' EOL='' MODE='title' SAVE=0 RESTORE=0
+do_bel=0
+do_save=0
+do_restore=0
+do_wname=0
 
-while getopts "ersw" OPT; do
+while getopts "arsw" OPT; do
 	case $OPT in
-	e) ESC='\\e' ST='\\e\\\\' BEL='\\007' EOL='\n';;
-	r) RESTORE=0;;
-	s) SAVE=1;;
-	w) MODE='wname';;
+	a) do_bel=1;;
+	r) do_restore=1;;
+	s) do_save=1;;
+	w) do_wname=1;;
 	*) usage; exit 2;;
 	esac
-done
+done; shift $((OPTIND-1))
 
-case $MODE in
-'title')
-	case $TERM in
-	[xkE]term*|rxvt*|cygwin|dtterm|termite|tmux*)
-		fmt="${ESC}]0;%s${BEL}";;
-	screen*)
-		fmt="${ESC}k%s${ST}";;
-	vt300*)
-		fmt="${ESC}]21;%s${ST}";;
-	*)
-		fmt="";;
-	esac;;
-'wname')
-	case $TERM in
-	screen*)
-		fmt="${ESC}k%s${ST}";;
-	*)
-		fmt="";;
-	esac;;
-esac
+title=$*
 
-title=${!OPTIND}
-
-if [[ $fmt ]]; then
-	if (( SAVE )); then
-		fmt="${ESC}[22;2t${fmt}"
-	elif (( RESTORE )); then
-		fmt="${ESC}[23;2t"
+if (( do_wname )); then
+	# Set tmux/screen window title
+	if (( do_save || do_restore )); then
+		echo "${0##*/}: save/restore ineffective for window name" >&2
+		exit 1
+	fi
+	if (( do_bel )); then
+		echo "${0##*/}: BEL terminator not used with this mode" >&2
+		exit 1
+	fi
+	printf '\ek%s\e\\' "$title"
+elif (( do_restore )); then
+	# Restore (pop) window title if supported
+	if [[ $title ]]; then
+		echo "${0##*/}: cannot both restore and set new title" >&2
+		exit 1
+	fi
+	if (( do_bel )); then
+		echo "${0##*/}: BEL terminator not used with this mode" >&2
+		exit 1
+	fi
+	printf '\e[23;2t'
+else
+	# Set regular Xterm window titlebar
+	if (( do_save )); then
+		# Save (push) window title if supported
+		printf '\e[22;2t'
+	fi
+	# XXX: Should just use BEL everywhere for better compatibility?
+	if (( do_bel )); then
+		printf '\e]0;%s\a' "$title"
+	else
+		printf '\e]0;%s\e\\' "$title"
 	fi
 fi
-
-printf "${fmt}${EOL}" "$title" >&2
