termprogress: clean up

diff --git a/misc/termprogress b/misc/termprogress
--- a/misc/termprogress
+++ b/misc/termprogress
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
-# Update the "progress" indicator in ConEmu and Windows Terminal
+# termprogress -- update the terminal window "progress" indicator
+#
+# Currently supported by ConEmu and Windows Terminal.
 
 readonly Remove=0
 readonly Normal=1
@@ -8,49 +10,50 @@ readonly Indeterminate=3
 readonly Paused=4
 
 usage() {
-	echo "Usage: ${0##*/} [-pe] VALUE"
+	echo "Usage: ${0##*/} [-p] [-e] <percent>"
 	echo "       ${0##*/} -i"
 	echo "       ${0##*/} -r"
-	echo
+	echo ""
+	echo "Update the terminal's \"progress\" indicator."
+	echo ""
+	echo "Options:"
 	echo "  -p            indicate 'paused' state"
 	echo "  -e            indicate 'error' state"
 	echo "  -i            indeterminate progress"
 	echo "  -r            remove all indicators"
 }
 
-state=$Normal
-value=0
-
-if (( ! $# )); then
-	usage; exit 2
-fi
+mode=
+value=
 
 while getopts "eipr" OPT; do
 	case $OPT in
-	e) state=$Error;;
-	i) state=$Indeterminate;;
-	p) state=$Paused;;
-	r) state=$Remove;;
-	*) exit 2;;
+	e) mode=$Error;;
+	i) mode=$Indeterminate;;
+	p) mode=$Paused;;
+	r) mode=$Remove;;
+	*) usage; exit 2;;
 	esac
 done; shift $((OPTIND-1))
 
 if [[ $1 ]]; then
-	if (( state == Indeterminate )); then
-		echo "${0##*/}: value ignored in indeterminate mode" >&2
-	elif (( state == Remove )); then
-		echo "${0##*/}: value ignored when removing progress" >&2
-	elif [[ $1 =~ ^[[:digit:]]+$ ]] && (( $1 >= 0 && $1 <= 100 )); then
-		value=$1
-	else
-		echo "${0##*/}: value must be a number between 0 and 100" >&2
+	if ! [[ $1 =~ ^([[:digit:]]{1,2}|100)$ ]]; then
+		echo "${0##*/}: percent must be an integer value [0-100]" >&2
 		exit 2
 	fi
+	mode=${mode:-$Normal}
+	value=$1
+	if (( mode == Indeterminate || mode == Remove )); then
+		echo "${0##*/}: progress value ignored in this mode" >&2
+	fi
 else
-	if (( state == Paused || state == Error )); then
-		echo "${0##*/}: value should be provided in paused/error modes too" >&2
+	if [[ ! $mode ]]; then
+		echo "${0##*/}: neither mode nor progress provided" >&2
+		exit 2
+	elif (( mode == Normal || mode == Paused || mode == Error )); then
+		echo "${0##*/}: progress value required in this mode" >&2
 		exit 2
 	fi
 fi
 
-printf '\e]9;4;%d;%d\e\\' "$state" "$value"
+printf '\e]9;4;%d;%d\e\\' "$mode" "$value"
