clean up libraries and ssh-authz-update

diff --git a/ssh/ssh-authz-update b/ssh/ssh-authz-update
--- a/ssh/ssh-authz-update
+++ b/ssh/ssh-authz-update
@@ -1,5 +1,18 @@
 #!/usr/bin/env bash
-shopt -s extglob
+# ssh-authz-update - authorized_keys updater tool
+#
+# Supports filtering keys by hostname or FQDN.
+#   - Start filtered region with '#if <glob>' where <glob> is bash's extended glob.
+#     <glob> will be checked against both the hostname from $(hostname) and the FQDN from DNS.
+#   - There is no '#elseif' or nesting; use '#if' to start a new region.
+#   - End region with '#endif'.
+# Example:
+#   ssh-rsa .... global key
+#   #if *.cluenet.org
+#   ssh-rsa .... cluenet-only key
+#   #if @(*.home|*.nullroute.eu.org)
+#   ssh-rsa .... home-only key
+#   #endif
 
 SOURCE_URL="http://purl.net/net/grawity/files/authorized_keys.txt"
 SIGNER_KEY_ID="D24F6CB2C1B52632"
@@ -7,34 +20,36 @@ SIGNER_KEY_FP="2357E10CEF4F7ED27E233AD5D24F6CB2C1B52632"
 KEYSERVER="pgp.surfnet.nl"
 
 PATH="$HOME/code/bin:$PATH"
+VERBOSE=""
+FQDN=$(fqdn) || exit 1
+
+. lib.bash		|| exit 1
+. libhttpfetch.bash	|| exit 1
 
 usage() {
-	echo "Usage: sshupdate-gpg [-r] [-v]"
-	echo
+	echo "Usage: $progname [-r] [-v]"
+	echo ""
 	echo "  -r  retrieve key"
 	echo "  -v  verbose mode"
-	echo
-	echo "WARNING: Running this script will replace your keys with grawity's!"
+	echo ""
+	echo -e "\e[1m""WARNING: Running this script will replace your keys with grawity's!""\e[m"
 	echo ""
 	echo "Key locations are hardcoded in $0."
+	exit 2
 } >&2
-
-have() { command -v "$1" &> /dev/null; }
-
-. ~/code/lib/bash/http_fetch || exit 1
 
 recv_key() {
 	local grip=$1
 	local server=$KEYSERVER
-	$VERBOSE && echo "sshup: recv-key $grip from $server"
+	say "updating key $grip from $server"
 	local out=$(gpg --status-fd 1 --keyserver "$server" --recv-key "$grip" 2>&1)
 	local gpg_status=$?
 	if ! grep -qs "^\[GNUPG:\] IMPORT_OK " <<< "$out"; then
 		[[ $out ]] && echo "$out" >&2
-		echo "sshup: fetching key $grip from $server failed (gpg returned $gpg_status)" >&2
+		warn "receiving key $grip from $server failed (gpg returned $gpg_status)"
 		return 1
 	else
-		$VERBOSE && echo "$out"
+		say "$out"
 		return 0
 	fi
 }
@@ -43,55 +58,61 @@ tryfetch() {
 	local url=$1 out=$2
 	local max_tries=3 retry_wait=3 attempt=0
 	while (( ++attempt <= max_tries )); do
-		$VERBOSE && echo "Fetching $url (attempt $attempt)"
+		say "fetching $url (attempt $attempt)"
 		if http_fetch "$url" "$out"; then
 			return 0
 		else
 			rm -f "$out"; sleep $retry_wait
 		fi
 	done
-	echo "sshup: gave up fetching $url after $attempt tries" >&2
+	warn "gave up fetching $url after $attempt tries"
 	return 1
 }
 
 verify() {
 	local file=$1
+	debug "verifying signature of '$file'"
 	local out=$(gpg --status-fd 1 --verify "$file" 2>/dev/null)
 	if grep -Eqs "^\[GNUPG:\] (ERROR|NODATA|BADSIG)( |\$)" <<< "$out" ||
 		! grep -qs "^\[GNUPG:\] GOODSIG $SIGNER_KEY_ID " <<< "$out" ||
 		! grep -qs "^\[GNUPG:\] VALIDSIG $SIGNER_KEY_FP " <<< "$out" ||
 		! grep -qs "^\[GNUPG:\] TRUST_ULTIMATE\$" <<< "$out"
 	then
-		{ echo "$out"; echo "sshup: failed to verify $file"; } >&2
+		{ echo "$out"; echo "$progname: failed to verify $file"; } >&2
 		return 1
 	else
-		$VERBOSE && echo "$out"
+		say "$out"
 		return 0
 	fi
 }
 
-hostmask_match() {
+host_match() {
 	local mask=$1
-	
-	[[ $FQDN == $mask || $HOSTNAME == $mask ]]
+	debug "matching '$FQDN', '$HOSTNAME' against '$mask'"
+	(shopt -s extglob;
+		[[ $FQDN == $mask || $HOSTNAME == $mask ]])
 }
 
 filter_keys() {
-	local line='' masked=false mask='' matched=false
+	local line='' masked=false mask='' matched=false skipped=0 
 	while read -r line; do
-		if [[ "$line" == '#if '* ]]; then
+		if [[ $line == '#if '* ]]; then
 			masked=true
 			mask=${line#'#if '}
-			if hostmask_match "$mask"; then
+			if host_match "$mask"; then
 				matched=true
 			else
 				matched=false
 			fi
+			skipped=0
+			debug "start masked region, mask='$mask', matched=$matched"
 			continue
-		elif [[ "$line" == '#endif' ]]; then
+		elif [[ $line == '#endif' ]]; then
 			masked=false
+			debug "end masked region, skipped $skipped lines"
 			continue
 		elif $masked && ! $matched; then
+			((++skipped))
 			continue
 		else
 			echo "$line"
@@ -99,21 +120,18 @@ filter_keys() {
 	done
 }
 
-umask 077
-
-FQDN=$(fqdn) || exit 1
-
 debug=":"
-VERBOSE=false
 
 while getopts "D:hvr" OPT "$@"; do
 	case "$OPT" in
 	'D')	debug+="${OPTARG}:";;
 	'v')	VERBOSE=true ;;
-	'r')	recv_key "$SIGNER_KEY_FP" &&
-		echo -e 'trust\n5\ny\nquit\n' |
-		gpg --batch --command-fd=0 --edit-key "$SIGNER_KEY_FP";;
-	'?')	usage; exit 2 ;;
+	'r')	if confirm "import key ${SIGNER_KEY_FP}?"; then
+			recv_key "$SIGNER_KEY_FP" &&
+			echo -e 'trust\n5\ny\nquit\n' |
+			gpg --batch --command-fd=0 --edit-key "$SIGNER_KEY_FP"
+		fi;;
+	'?')	usage;;
 	esac
 done
 
@@ -123,14 +141,16 @@ if [[ $debug == *:filter:* ]]; then
 fi
 
 if ! have gpg; then
-	echo "sshup: 'gpg' not found in \$PATH" >&2
-	exit 1
+	die "'gpg' not found in \$PATH"
 fi
 
 if ! gpg --list-keys "$SIGNER_KEY_FP" &> /dev/null; then
-	echo "sshup: signer key $SIGNER_KEY_FP not in keyring" >&2
-	exit 1
+	die "key $SIGNER_KEY_FP not in keyring (use ${progname} -r to import)"
 fi
+
+# main code
+
+umask 077
 
 mkdir -pm 0700 ~/.ssh
 
@@ -138,8 +158,7 @@ recv_key "$SIGNER_KEY_FP" >&2 || exit 1
 
 temp=$(mktemp ~/.ssh/authorized_keys.XXXXXX)
 if ! tryfetch "$SOURCE_URL" "$temp"; then
-	echo "sshup: failed to fetch $SOURCE_URL" >&2
-	exit 1
+	die "failed to fetch $SOURCE_URL"
 fi
 
 if verify "$temp"; then
@@ -150,8 +169,9 @@ if verify "$temp"; then
 	rm -f "$temp"
 fi
 
-if [ -f ~/.ssh/authorized_keys.local ]; then
+if [[ -s ~/.ssh/authorized_keys.local ]]; then
 	{
+		echo ""
 		echo "# keys from ~/.ssh/authorized_keys.local"
 		cat ~/.ssh/authorized_keys.local
 	} | filter_keys >> ~/.ssh/authorized_keys
