remove usage of notice() from bash code

diff --git a/bin/annex b/bin/annex
--- a/bin/annex
+++ b/bin/annex
@@ -31,7 +31,7 @@ elif [[ $cmd == @(add|copy|fsck|get|import|move|push|reinject) ]]; then
             debug "nocache: found '$lib' in \$LD_PRELOAD"
         fi
     else
-        notice "nocache: '$lib' not found; may hurt performance"
+        warn "nocache: '$lib' not found; may hurt performance"
     fi
 else
     debug "nocache: disabled for command '$cmd'"
@@ -253,12 +253,12 @@ case $cmd in
             else
                 url=$(attr -L -q -g xdg.origin.url "$file" 2>/dev/null)
                 if [[ $url == https://dynasty-scans.com/* ]]; then
-                    notice "ignoring blacklisted origin '$url' for file '$file'" >&2
+                    warn "ignoring blacklisted origin '$url' for file '$file'" >&2
                 elif [[ $url == @(http|https|ftp)://* ]]; then
                     info "adding origin '$url' to file '$file'" >&2
                     echo "$url $file"
                 elif [[ $url ]]; then
-                    notice "ignoring non-web origin '$url' for file '$file'" >&2
+                    warn "ignoring non-web origin '$url' for file '$file'" >&2
                 else
                     warn "no origin URL for file '$file'" >&2
                 fi
