flatten bin/ symlinks (most of them)

diff --git a/bin/backup b/bin/backup
--- a/bin/backup
+++ b/bin/backup
@@ -1,1 +1,222 @@
-../misc/backup
+#!/usr/bin/env bash
+
+PATH="$HOME/code/backup:$PATH"
+
+. lib.bash || exit
+. libks.bash || exit
+
+progname_prefix=0
+
+# configuration
+
+local_config_file=$path_config/backup.conf.sh
+
+default_jobs=(push-hd)
+hosts=()
+borg_args=()
+borg_root_repo="/vol4/Backup/Roots/$HOSTNAME.borg"
+borg_home_repo="/vol4/Backup/Homes/$HOSTNAME.borg"
+rsync_base_dir="$HOME/Backup"
+
+# Used by backup.conf to override borg_* config variables at job run time
+borg_pre() { true; }
+
+if [[ -f $local_config_file ]]; then
+	. "$local_config_file" || die "failed to load configuration from '$local_config_file'"
+else
+	warn "config file '$local_config_file' missing"
+fi
+
+if [[ $push_volume ]]; then
+	notice "obsolete \$push_volume defined in ${local_config_file@Q}"
+fi
+
+# misc
+
+conf=$path_config/synced
+
+lock_path=
+lock_fd=
+failed_jobs=()
+
+take_lock() {
+	local job=$1
+
+	lock_path=${XDG_RUNTIME_DIR?}/backup-$1.lock
+	exec {lock_fd}<>$lock_path
+	flock -x -n $lock_fd || {
+		if read ldate < "$lock_path" || true; then
+			lmsg="started on $(date -d "${ldate%% *}" +"%F %T")"
+		else
+			lmsg="status unknown"
+		fi
+		die "job '$job' is already running ($lmsg)"
+	}
+	echo "$(date -Isecond) $*" >&$lock_fd
+}
+
+drop_lock() {
+	exec {lock_fd}<&-
+	rm -f "$lock_path"
+}
+
+is_mounted() {
+	local path=$1
+	test -d "$path" && mountpoint -q "$path"
+}
+
+is_older_than() {
+	local path=$1 seconds=$2
+	local a=$(date +%s)
+	local b=$(stat -c %Y "$path" 2>/dev/null || echo 0)
+	(( a - b > seconds ))
+}
+
+do_borg() {
+	local kind=$1
+	local tag="$HOSTNAME.$(date +%Y%m%d.%H%M)"
+	local var
+
+	borg_pre "$kind"
+	var="borg_${kind}_repo"; local repo="${!var}"
+	var="borg_${kind}_dirs[@]"; local dirs=("${!var}")
+	var="borg_${kind}_args[@]"; local args=("${!var}")
+
+	if [[ ! $repo ]]; then
+		die "borg_${kind}_repo not defined"
+	fi
+	if ! [[ $repo == *:* || -d $repo ]]; then
+		die "repository '$repo' does not exist"
+	fi
+	if [[ $borg_args ]]; then
+		die "borg_args cannot be changed anymore"
+	fi
+	if [[ $dirs ]]; then
+		die "borg_${kind}_dirs cannot be changed anymore"
+	fi
+	if [[ $args ]]; then
+		die "borg_${kind}_args cannot be changed anymore"
+	fi
+
+	~/bin/misc/backup.py \
+		--borg-repo="$repo" \
+		"$kind"
+}
+
+do_job() {
+	$0 "$1" || { failed_jobs+=("$1"); false; }
+}
+
+job_main() {
+	case $job in
+		home | borg-home)
+			do_borg home
+			;;
+		root | borg-root)
+			do_borg root
+			;;
+		servers)
+			homes=()
+			roots=()
+			for host in "${hosts[@]}"; do
+				if [[ $host == '#'* ]]; then
+					continue
+				elif [[ $host == *'!' ]]; then
+					host=${host%!}
+					roots+=($host)
+				fi
+				homes+=($host)
+			done
+			debug "backup home from: ${homes[*]}"
+			debug "backup rootfs from: ${roots[*]}"
+			debug "running jobs"
+			for host in ${homes[@]}; do
+				do_job @$host
+			done
+			for host in ${roots[@]}; do
+				do_job root@$host
+			done
+			;;
+		root@*)
+			host=${job#*@}
+			~/bin/misc/do_rsync \
+				"root@$host:/" \
+				"$rsync_base_dir/Roots/$host/" \
+				-f "merge $conf/rsync-filters/server_root_all"		\
+				-f "merge $conf/rsync-filters/server_root_extra"	\
+				-f "merge $conf/rsync-filters/server_root_$host"	\
+				-F -x -P --fake-super					;
+			;;
+		@*)
+			host=${job#@}
+			~/bin/misc/do_rsync \
+				"$host:" \
+				"$rsync_base_dir/Homes/$host/" \
+				-f "merge $conf/rsync-filters/home_all"			\
+				-f "merge $conf/rsync-filters/home_$host"		\
+				-f "merge $conf/rsync-filters/server_home_all"		\
+				-f "merge $conf/rsync-filters/server_home_$host"	\
+				-F -x -P						;
+			;;
+		gphotos)
+			src="gphotos:media/by-year"
+			dst="/vol4/Backup/Google Drive Photos"
+			if [[ ! -d "$dst" ]]; then
+				confirm "missing '$dst', create?" || exit
+			fi
+			do: rclone sync -v "$src" "$dst"
+			;;
+		irc)
+			. ~/.config/nullroute.eu.org/synced/irc.conf
+			~/bin/misc/do_rsync \
+				"$irc_host:$irc_log_path/" \
+				~/Attic/Chatlogs/current/
+			;;
+		*)
+			die "unknown job '$job'"
+			;;
+	esac
+}
+
+# Main task
+
+if [[ ! $_inhibited ]]; then
+	export _inhibited=$$
+	debug "restarting under gnome-inhibit"
+	exec gnome-inhibit \
+		--always \
+		--who "backup" \
+		--what "suspend" \
+		--why "Performing a backup" \
+		-- "$0" "$@"
+fi
+
+set -e
+umask 077
+debug "started with: '$*'"
+
+trap "die \"[\$BASHPID] '\$job' interrupted\"" INT
+
+(( $# )) || set -- "${default_jobs[@]}"
+
+for job; do
+	take_lock "$job"
+	log2 "running job '$job'"
+	t_begin=$(date +%s)
+
+	job_main || r=$?
+
+	t_end=$(date +%s)
+	lib:echo "Job '$job' finished in $(interval $[t_end-t_begin])"
+	drop_lock
+
+	if (( r )); then
+		failed_jobs+=("$job")
+		break
+	fi
+done
+
+if (( ${#failed_jobs[@]} )); then
+	_fail=${failed_jobs[*]}
+	err "backup failed for ${_fail// /, }"
+fi
diff --git a/bin/git-up b/bin/git-up
--- a/bin/git-up
+++ b/bin/git-up
@@ -1,1 +1,55 @@
-../devel/git-up
+#!/usr/bin/env bash
+# git-up - fast-forward the latest changes from upstream
+
+. lib.bash || exit
+
+check_master_rename() {
+	# Running in a subshell, with the repository as cwd.
+	if [ -e .git/refs/remotes/origin/main ]; then
+		if [ "$(< .git/HEAD)" = "ref: refs/heads/master" ]; then
+			echo "looks like master branch was renamed, following"
+			git branch -m main &&
+			git branch -u origin/main &&
+			git remote set-head origin -a
+		fi
+	fi
+}
+
+git_up_here() {
+	# Running in a subshell, with the repository as cwd.
+	set -e
+
+	if ! git rev-parse --git-dir >&/dev/null; then
+		echo "error: '$PWD' is not a Git repository" >&2
+		return 1
+	fi
+
+	old=$(git rev-parse "HEAD")
+	if [ -e .git/svn ]; then
+		~/bin/bin/pull .
+	else
+		git fetch
+		if [ "$(git rev-parse --is-bare-repository)" != "true" ]; then
+			check_master_rename
+			git pull --ff-only --no-stat --no-recurse-submodules
+		fi
+	fi
+	new=$(git rev-parse "HEAD")
+
+	if [ "$new" != "$old" ]; then
+		opts=$(git config --get-all nullroute.git-new.options || true)
+		paths=$(git config --get-all nullroute.git-new.paths || true)
+		# Not using "@{1}.." because reflogs aren't always available in
+		# bare repositories.
+		settitle "git up [${PWD/#"$HOME/"/"~/"}]"
+		tig $opts "$old..$new" -- $paths
+	fi
+}
+
+(( $# )) || set -- "."
+
+err=0
+for repo in "$@"; do
+	(cd "$repo" && git_up_here) || err=1
+done
+exit $err
diff --git a/bin/hpavctl b/bin/hpavctl
--- a/bin/hpavctl
+++ b/bin/hpavctl
@@ -1,1 +1,278 @@
-../net/hpavctl
+#!/usr/bin/env bash
+
+. lib.bash || exit
+. libks.bash || exit
+
+usage() {
+	cmds=(
+		"devices [mac]"
+		"peers [mac]"
+		"topology"
+		"show-local-pib"
+		"set-local-nmk <nmk> [mac]"
+		"set-remote-nmk <nmk> <mac> <dak> <via_mac>"
+		"reboot <mac>"
+		"reset-to-factory <mac>"
+	)
+	echo "usage: $progname <cmd> ..."
+	echo ""
+	for c in "${cmds[@]}"; do
+		echo "  $progname $c"
+	done
+}
+
+pretty_nw_info() {
+	local hed tail
+	while read -r head tail; do
+		set -- $tail
+		local -A kv=()
+		case $head in
+		NID)
+			set -- NID "$@"
+			while (( $# )); do kv[$1]=$2; shift; shift; done
+			echo "Network ID: ${kv[NID]} (short: ${kv[SNID]})"
+			;;
+		CCO)
+			printf "\n"
+			printf "\e[1m* %s\e[m\n" "Central Coordinator:" ;;&
+		STA)
+			printf "\n"
+			printf "\e[1m* %s\e[m\n" "Station:" ;;&
+		CCO|STA)
+			while (( $# )); do kv[$1]=$2; shift; shift; done
+			local location=${locations[${kv[MAC]}]}
+			local model=${models[${kv[MAC]}]}
+			[[ ${kv[MAC]} ]] &&
+			printf "   MAC address: \e[38;5;10m%s\e[m \e[38;5;8m%s\e[m\n" "${kv[MAC]}" "$(_get_vendor ${kv[MAC]})"
+			[[ $location || $model ]]  &&
+			printf "   Description: \e[38;5;11m%s\e[m \e[36m(%s)\e[m\n" "$location" "$model"
+			[[ ${kv[TX]} ]] && tx=$[10#${kv[TX]}]
+			[[ ${kv[RX]} ]] && rx=$[10#${kv[RX]}]
+			[[ ${kv[TX]} && ${kv[RX]} ]] &&
+			printf "   Speed:       %s Mbps TX / %s Mbps RX\n" "$tx" "$rx"
+			[[ ${kv[BDA]} ]] &&
+			printf "   Bridged to:  %s \e[38;5;8m%s\e[m\n" "${kv[BDA]}" "$(_get_vendor ${kv[BDA]})"
+			;;
+		esac
+	done
+}
+
+valid_dak() {
+	[[ $1 == key[12] ]] ||
+	[[ $1 =~ ^([0-9A-Fa-f]{2}:?){15}[0-9A-Fa-f]{2}$ ]]
+}
+valid_mac() {
+	[[ $1 == @(local|all|broadcast) ]] ||
+	[[ $1 =~ ^([0-9A-Fa-f]{2}:?){5}[0-9A-Fa-f]{2}$ ]]
+}
+valid_nid() {
+	err "TODO: don't know NID rules yet"
+}
+valid_nmk() {
+	[[ $1 == @(key[12]|none) ]] ||
+	[[ $1 =~ ^([0-9A-Fa-f]{2}:?){15}[0-9A-Fa-f]{2}$ ]]
+}
+
+__check() {
+	if [[ ! $1 ]]; then
+		die "missing ${3}${4:+ (}${4}${4:+)}"
+	elif ! valid_$2 "$1"; then
+		die "bad $3 '$1'"
+	fi
+}
+check_dak!() {
+	__check "$1" dak "device access key"
+}
+check_mac!() {
+	__check "$1" mac "device address" "MAC or 'local' or 'broadcast'"
+}
+check_nid!() {
+	__check "$1" nid "network identifier"
+}
+check_nmk!() {
+	__check "$1" nmk "network membership key"
+}
+
+_check_dak!() {
+	local -n v=$1
+	if [[ $v == @* ]]; then
+		local _v=$(getnetrc -sdf %p "dak/$v")
+		if [[ $_v ]]; then
+			v=$_v
+		fi
+	fi
+	case $v in
+		????-????-????-????) v=$(hpavkey -D "$v");;
+	esac
+	check_dak! "$v"
+}
+_check_mac!() {
+	local -n v=$1
+	case $v in
+		a|all) v=broadcast;;
+		b|bcast) v=broadcast;;
+		l|local) v=local;;
+	esac
+	check_mac! "$v"
+}
+_check_nid!() {
+	local -n v=$1
+	check_nid! "$v"
+}
+_check_nmk!() {
+	local -n v=$1
+	case $v in
+		????-????-????-????) v=$(hpavkey -M "$v");;
+		default|HomePlugAV) v=key1;;
+	esac
+	check_nmk! "$v"
+}
+
+call() {
+	do: "$1" "${opts[@]}" "${@:2}"
+}
+
+declare -A locations=()
+declare -A models=()
+
+declare -- dev=
+declare -- dak=
+declare -a opts=()
+declare -i verbose=0
+
+if [[ -e "$path_config/hpavctl.conf.sh" ]]; then
+	. "$path_config/hpavctl.conf.sh" || exit
+fi
+
+while getopts ":D:i:v" OPT; do
+	case $OPT in
+	D) dak=$OPTARG;;
+	i) dev=$OPTARG;;
+	v) verbose+=1;;
+	*) lib:die_getopts;;
+	esac
+done; shift $((OPTIND-1))
+
+(( $# )) || set -- net
+
+if [[ $dak ]]; then
+	_check_dak! dak
+	info "using device access key $dak"
+	opts+=(-D "$dak")
+fi
+
+if [[ ! $dev ]]; then
+	for path in /sys/class/net/*; do
+		if [[ $(< $path/type) == 1 ]] &&
+		   [[ $(< $path/operstate) == up ]] &&
+		   [[ ! -e $path/bridge ]]; then
+			dev=${path##*/}
+			debug "selecting interface '$dev'"
+			break
+		fi
+	done
+fi
+if [[ ! $dev ]]; then
+	die "interface not specified (use -i)"
+elif [[ ! -e /sys/class/net/$dev ]]; then
+	die "interface '$dev' does not exist"
+elif [[ $(< /sys/class/net/$dev/operstate) == down ]]; then
+	die "interface '$dev' is down"
+elif [[ $(< /sys/class/net/$dev/operstate) != up ]]; then
+	warn "interface '$dev' seems to be down"
+fi
+opts+=(-i "$dev")
+
+_grep_hwdb() {
+	systemd-hwdb query "$1" | sed -n "s/^$2=//p"
+}
+
+_get_vendor() {
+	local mac=$1 vendor
+	vendor=$(_grep_hwdb "OUI:${mac//:/}" ID_OUI_FROM_DATABASE)
+	echo "($vendor)"
+}
+
+cmd=$1
+case $cmd in
+	devices|dev)
+		mac=${2:-broadcast}; _check_mac! mac
+		# VS_NW_INFO + VS_SW_VER
+		call plcstat -t $mac
+		# VS_SW_VER, one device only
+		#call plctool -q -r $mac
+		;;
+	network|net|peers|topo|topology)
+		mac=${2:-local}; _check_mac! mac
+		if (( verbose >= 3 )); then
+			# VS_NW_INFO + VS_SW_VER
+			call plcstat -t $mac
+		elif (( verbose >= 2 )); then
+			# VS_NW_INFO
+			call plctool -m $mac
+		elif (( verbose >= 1 )); then
+			# VS_NW_INFO
+			call plcstat -m $mac
+		elif [[ $mac == broadcast ]]; then
+			call plctool -q -r $mac |
+			while read -r _dev _mac _; do
+				echo "--- $_mac ---"
+				# VS_NW_INFO
+				call plcstat -m $_mac
+			done
+		else
+			# VS_NW_INFO
+			call plcstat -m $mac | pretty_nw_info
+		fi
+		;;
+	statistics|stat)
+		clear=''
+		mac=${2:-local}
+		if [[ $mac == clear ]]; then
+			clear='-C'
+			mac=${3:-local}
+		fi
+		call plcstat -s CSMA-ALL -d both $clear $mac
+		;;
+	show-local-pib|pib)
+		mac=${2:-local}
+		[[ $mac == local ]] || die "PIB query only supported for local device"
+		call plctool -I
+		;;
+	set-local-nmk)
+		[[ $2 ]] || die "Usage: $cmd <nmk> [mac]"
+		nmk=$2; _check_nmk! nmk
+		mac=${3:-local}; _check_mac! mac
+		info "setting NMK at '$mac' (via Ethernet)"
+		debug "setting network membership key '$nmk'"
+		call plctool -M -K "$nmk" "$mac"
+		;;
+	set-remote-nmk)
+		[[ $5 ]] || die "Usage: $cmd <nmk> <mac> <dak> <via_mac>"
+		nmk=$2; _check_nmk! nmk
+		rmac=$3; _check_mac! rmac
+		dak=$4; _check_dak! dak
+		lmac=$5; _check_mac! lmac
+		info "setting NMK at '$rmac' (via Powerline through '$lmac')"
+		debug "using device access key '$dak'"
+		debug "setting network membership key '$nmk'"
+		call plctool -J "$rmac" -D "$dak" -K "$nmk" "$lmac"
+		;;
+	reboot)
+		mac=$2; _check_mac! mac
+		info "rebooting device '$mac'"
+		call plctool -R "$mac"
+		;;
+	reset-to-factory)
+		mac=$2; _check_mac! mac
+		confirm "reset device '$mac'?" || exit
+		info "resetting device '$mac' to factory defaults"
+		call plctool -T "$mac"
+		;;
+	generate-password|pwgen)
+		mac2pw -q -l 16 -b 4 -n ${2:-1} 00B052000001;;
+	"")
+		die "missing command";;
+	*)
+		die "unknown command '$1'";;
+esac
diff --git a/bin/ssh-pkcs11 b/bin/ssh-pkcs11
--- a/bin/ssh-pkcs11
+++ b/bin/ssh-pkcs11
@@ -1,1 +1,41 @@
-../security/ssh-pkcs11
+#!/usr/bin/env bash
+# ssh-pkcs11 -- Wrapper which allows directly using PKCS#11 modules with tools
+# that rely on ssh-agent (such as `ssh-keygen -Y sign`).
+#
+# Note: ssh-keygen supports -D and -I options when signing certificates using a
+# CA key, but oddly not when signing data via -Y.
+
+dirs=(/usr/lib/pkcs11 /usr/lib)
+lib='p11-kit-proxy.so'
+do_add=0
+
+while getopts "a" OPT; do
+	case $OPT in
+	a) do_add=1;;
+	*) exit 2;;
+	esac
+done; shift $((OPTIND-1))
+
+if [[ ! $_SSH_PKCS11_MOD ]]; then
+	if [[ $lib != */* ]]; then
+		for dir in "${dirs[@]}"; do
+			if [[ -e $dir/$lib ]]; then
+				lib=$dir/$lib
+				break
+			fi
+		done
+	fi
+	if [[ $lib != */* ]]; then
+		echo "${0##*/}: Could not find PKCS#11 library '$lib'" >&2
+		exit 1
+	fi
+	if (( do_add )); then
+		ssh-add -s "$lib"
+	else
+		export _SSH_PKCS11_MOD=$lib
+		exec ssh-agent "$0" "$@"
+	fi
+else
+	ssh-add -s "$_SSH_PKCS11_MOD" &&
+	exec "$@" || exit
+fi
diff --git a/bin/tarball b/bin/tarball
--- a/bin/tarball
+++ b/bin/tarball
@@ -1,1 +1,178 @@
-../misc/tarball
+#!/usr/bin/env bash
+# tarball - archive away a directory
+
+. lib.bash || exit
+
+set -e
+
+opt_attributes=0
+
+usage() {
+	echo "Usage: $progname [-aAfkO] <directory> [<archive>]"
+	echo ""
+	echo_opt "-a" "keep extended attributes"
+	echo_opt "-A" "do not automatically move archive to /home"
+	echo_opt "-f" "overwrite existing archive"
+	echo_opt "-k" "keep original directory"
+	echo_opt "-O" "set archive owner to that of original directory"
+}
+
+do_archive() {
+	local dir=$1 out=$2
+
+	if (( opt_attributes )); then
+		lib:echo "dumping extended attributes"
+		local attr_tmp=$(mktemp /tmp/attrib.XXXXXXXX)
+		getfattr -Rhd "$dir" \
+			| grep -v '^user\.com\.dropbox\.' \
+			| sed 's/^user\.org\.eu\.nullroute\./user.http./' \
+			> "$attr_tmp"
+		if [[ -s "$attr_tmp" ]]; then
+			mv "$attr_tmp" "$dir/_attributes"
+		else
+			rm -f "$attr_tmp"
+		fi
+	fi
+
+	lib:echo "archiving files"
+	set -o pipefail
+	case $out in
+	    *.tgz) tar -cvzf "$out" "$dir" | progress;;
+	    *.zip) zip -ry "$out" "$dir";;
+	esac || return
+
+	[[ -s "$out" ]] || { rm -f "$out"; false; }
+}
+
+get_timestamp() {
+	local t=$(find "$1" -type f -not -name '_attributes' -printf '%Ts\n' \
+		| sort -n | tail -1)
+	[[ $t ]] || t=$(find "$1" -maxdepth 0 -type d -printf '%Ts\n')
+	echo $t
+}
+
+get_fstag() {
+	local dir=$1;				debug "dir='$dir'"
+	if [[ -e $dir ]]; then
+		local fsid=$(stat -fc %i "$dir");	debug " - fsid='$fsid'"
+		local mtpt=$(stat -c %m "$dir");	debug " - mount='$mtpt'"
+		local devno=$(mountpoint -d "$mtpt");	debug " - devno='$devno'"
+		echo "$fsid,$mtpt,$devno"
+	else
+		echo "-,$dir,-"
+	fi
+}
+
+# environment
+
+if (( UID == 0 )); then
+	umask 077
+fi
+
+if [[ ! $OLD_TAR ]]; then
+	export TAR_OPTIONS="--xattrs"
+fi
+
+# parse command line
+
+auto_move=0
+auto_remove=1
+do_chown=0
+do_overwrite=0
+
+case ${0##*/} in
+    tarball) ext=tgz;;
+    zipball) ext=zip;;
+esac
+
+while getopts ":aAfkO" OPT; do
+	case $OPT in
+	a) opt_attributes=1;;
+	A) auto_move=0;;
+	f) do_overwrite=1;;
+	k) auto_remove=0;;
+	O) do_chown=1;;
+	*) lib:die_getopts;;
+	esac
+done; shift $((OPTIND-1))
+
+dir=${1%/}
+
+if (( do_chown && UID != 0 )); then
+	die "must be root in order to change file ownership"
+fi
+
+if [[ ! $dir ]]; then
+	die "directory to archive not specified"
+elif [[ ! -d $dir ]]; then
+	die "path is not a directory"
+fi
+
+# prepare: find the timestamp
+
+ts=$(get_timestamp "$dir")
+debug "timestamp of '$dir' = '$ts'"
+
+if [[ ! $ts ]]; then
+	die "could not obtain timestamp of '$dir'"
+fi
+
+if [[ $2 == --now ]]; then
+	out=${dir}-$(date +%F).$ext
+elif [[ $2 == --date ]]; then
+	out=${dir}_$(date +%F -d "@$ts").$ext
+elif [[ -d $2 ]]; then
+	die "target '$2' already exists"
+else
+	out=${2:-$dir}.$ext
+fi
+
+if (( auto_move )); then
+	if ! case $(get_fstag "$dir") in
+		($(get_fstag ~)) true;;
+		($(get_fstag ~/Private)) true;;
+		(*) false;;
+	esac; then
+		out=~/$out
+	fi
+fi
+
+# check for existing archives
+
+for file in "$out"; do # "${1%/}".{{t,tar.}{gz,bz2,xz},zip}; do
+	if [[ -e "$file" ]]; then
+		if (( do_overwrite )); then
+			warn "archive already exists: $file"
+		else
+			die "archive already exists: $file"
+		fi
+	fi
+done
+
+# create the tarball/zipball
+
+log2 "creating archive \"$out\""
+
+if do_archive "$dir" "$out"; then
+	touch -d "@$ts" "$out"
+	chmod a-w "$out"
+	if (( do_chown )); then
+		owner=$(stat -c %u:%g "$dir")
+		chown "$owner" "$out"
+	fi
+	lib:echo "archived to \"$out\""
+	ls -lh "$out"
+	if (( auto_remove )); then
+		lib:echo "removing original"
+		if [[ -e ~/.local/share/Trash ]]; then
+			trash "$dir/"
+		else
+			rm -rf "$dir/"
+		fi
+		lib:echo "original directory removed"
+	else
+		lib:echo "original directory preserved"
+	fi
+else
+	die "archiving failed"
+fi
diff --git a/bin/update-authorized-keys b/bin/update-authorized-keys
--- a/bin/update-authorized-keys
+++ b/bin/update-authorized-keys
@@ -1,1 +1,213 @@
-../security/update-authorized-keys
+#!/usr/bin/env bash
+# ssh-authz-update - authorized_keys updater tool
+
+PATH="$HOME/bin:$HOME/code/bin:$PATH"
+
+. lib.bash || exit
+. libfilterfile.bash || exit
+. libhttpfetch.bash || exit
+
+progname_prefix=0
+
+usage() {
+	echo "Usage: $progname [-f] [-q] [-r [-k URI]]"
+	echo ""
+	echo_opt "-f" "proceed if opt-out or username mismatch was found"
+	echo_opt "-q" "quietly exit if update is not to be done"
+	echo ""
+	echo_opt "-r" "import the signing key from keyserver"
+	echo_opt "-k URL" "use another keyserver"
+}
+
+filter_keys() {
+	filter_file 'match_hostname'
+}
+
+recv_key() {
+	local key=$1 status=
+	debug "retrieving key '$key'"
+	if status=$($GPG --keyserver "$keyserver" --recv-key "$key" 2>&1); then
+		lib:trace "$status"
+	else
+		echo "$status" >&2
+		warn "failed to receive key $key from $keyserver"
+		return 1
+	fi
+}
+
+fetch() {
+	local url=$1 out=$2
+	local max_tries=3 retry_wait=3 attempt=1
+	while true; do
+		debug "fetching $url (#$attempt)"
+		if http_fetch "$url" "$out"; then
+			return 0
+		elif (( $? == 99 )); then
+			break
+		fi
+		rm -f "$out"
+		if (( attempt++ >= max_tries )); then
+			break
+		fi
+		sleep $retry_wait
+		(( retry_wait *= 2 ))
+	done
+	return 1
+}
+
+verify() {
+	local input=$1 output=$2 status= errors=0
+	debug "verifying '$input' to '$output'"
+	if status=$($GPG --batch --yes --status-fd 1 --output "$output" \
+	                 --trust-model pgp --decrypt "$input" 2> /dev/null); then
+		if ! grep -Eqs "^\\[GNUPG:\\] VALIDSIG $signer_fpr " <<< "$status"; then
+			err "file has invalid signature"
+		fi
+		if ! grep -Eqs "^\\[GNUPG:\\] TRUST_ULTIMATE( 0 .+)?\$" <<< "$status"; then
+			err "signer's key is not ultimately trusted"
+		fi
+		if (( errors )); then
+			echo "$status" >&2
+			return 1
+		else
+			lib:trace "$status"
+			return 0
+		fi
+	else
+		err "unknown GnuPG error occured"
+		echo "$status" >&2
+		return 1
+	fi
+}
+
+readonly src_url="http://nullroute.lt/~grawity/files/authorized_keys.txt"
+readonly dst_file="$HOME/.ssh/authorized_keys"
+readonly signer_fpr="2357E10CEF4F7ED27E233AD5D24F6CB2C1B52632"
+
+filter_test=0
+force=0
+import_key=0
+stayquiet=0
+keyserver="hkps://keyserver.ubuntu.com"
+
+while getopts ":Ffk:rq" OPT; do
+	case $OPT in
+	F) filter_test=1;;
+	f) force=1;;
+	k) keyserver=$OPTARG;;
+	r) import_key=1;;
+	q) stayquiet=1;;
+	*) lib:die_getopts;;
+	esac
+done
+
+umask 077
+
+if (( filter_test )); then
+	info "filter test mode"
+	if [[ -t 1 ]]; then
+		export FILTERDEBUG=1
+		exec >/dev/null
+	fi
+	filter_keys
+	exit
+fi
+
+if [[ -e ~/.ssh/authorized_keys.optout ]]; then
+	if (( force )); then
+		warn "found opt-out marker, but proceeding anyway"
+	elif (( !stayquiet )); then
+		die "found opt-out marker"
+	else
+		exit 0
+	fi
+fi
+
+if [[ $LOGNAME != grawity ]]; then
+	if [[ -e ~/.ssh/authorized_keys.optin ]]; then
+		debug "username does not match 'grawity' but opt-in file found"
+	elif (( force )); then
+		echo "Overridden by $LOGNAME on $(date)" > ~/.ssh/authorized_keys.optin
+		warn "username does not match 'grawity', proceeding anyway"
+	elif (( !stayquiet )); then
+		die "username does not match 'grawity'"
+	else
+		exit 0
+	fi
+fi
+
+# find the tool
+
+if have gpg2; then
+	GPG=gpg2
+elif have gpg; then
+	GPG=gpg
+else
+	die "'gpg' not found in \$PATH"
+fi
+
+# ensure key exists in keyring
+
+if (( import_key )); then
+	recv_key "$signer_fpr" || die "failed to import key '$signer_fpr'"
+	info "imported owner's key into keyring"
+	if confirm "mark this key as ultimately trusted?"; then
+		(echo "$signer_fpr:6:" | $GPG --import-ownertrust) &&
+		info "key's ownertrust updated"
+	else
+		die "only ultimately trusted keys are accepted"
+	fi
+elif ! [[ -d ~/.gnupg ]]; then
+	if (( !stayquiet )); then
+		die "GnuPG data directory is missing"
+	else
+		exit 0
+	fi
+elif ! $GPG --list-keys "$signer_fpr" > /dev/null; then
+	if (( !stayquiet )); then
+		die "Public key $signer_fpr not found in keyring"
+	else
+		exit 0
+	fi
+fi
+
+# download new pubkeys
+
+mkdir -p "${dst_file%/*}"
+
+tmp_signed=$(mktemp "$dst_file.XXXXXXXX")
+
+if ! fetch "$src_url" "$tmp_signed"; then
+	rm -f "$tmp_signed"
+	die "fetch of $src_url failed"
+elif ! test -s "$tmp_signed"; then
+	rm -f "$tmp_signed"
+	die "empty file fetched from $src_url"
+fi
+
+tmp_plain=$(mktemp "$dst_file.XXXXXXXX")
+
+if ! verify "$tmp_signed" "$tmp_plain"; then
+	rm -f "$tmp_plain"
+	die "verification of $tmp_signed failed"
+fi
+
+local_file="$dst_file.local"
+
+{
+	echo "# updated: at $(date +"%Y-%m-%d %H:%M:%S %z")"
+	echo "# updated: from $src_url"
+	cat "$tmp_plain"
+	if [[ -s $local_file ]]; then
+		echo "# updated: from $local_file"
+		cat "$local_file"
+	fi
+	echo "# updated: end"
+} | filter_keys > "$dst_file"
+
+rm -f "$tmp_plain" "$tmp_signed"
+
+if [[ -t 1 ]]; then
+	num=$(grep -c '^[^#]' "$dst_file")
+	info "imported $num authorized keys"
+fi
diff --git a/bin/vitables b/bin/vitables
--- a/bin/vitables
+++ b/bin/vitables
@@ -1,1 +1,38 @@
-../net/vitables
+#!/usr/bin/env bash
+# vitables -- interactively edit the current iptables ruleset
+
+. lib.bash || exit
+
+case ${0##*/} in
+	vi6tables)
+		iptables='ip6tables';;
+	vitables|*)
+		iptables='iptables';;
+esac
+
+temp=$(mktemp /tmp/iptables.XXXXXXXX.tmp)
+orig=$(mktemp /tmp/iptables.XXXXXXXX.tmp)
+r=0
+
+sudo $iptables-save > "$temp"
+cp "$temp" "$orig"
+
+while true; do
+	${EDITOR:-vi} "$temp"
+	if ! grep -qs '^[^#]' "$temp"; then
+		lib:echo "File empty, reload aborted" >&2
+		break
+	elif cmp -s "$temp" "$orig"; then
+		lib:echo "No changes made" >&2
+		break
+	elif sudo $iptables-restore < "$temp"; then
+		lib:echo "Rules reloaded successfully"
+		break
+	elif ! confirm "error: Failed to load rules; edit again?"; then
+		r=1
+		break
+	fi
+done
+
+rm -f "$temp" "$orig"
+exit $r
