remove most uses of find_file

diff --git a/bin/capture b/bin/capture
--- a/bin/capture
+++ b/bin/capture
@@ -36,7 +36,9 @@ done
 
 declare -A hosts=() interfaces=()
 
-lib::find_file config_file= ~/lib/capture.aliases config:capture.aliases && {
+alias_file=${XDG_CONFIG_HOME?}/nullroute.lt/capture.aliases
+
+if [[ -e $alias_file ]]; then
 	while IFS='=' read -r key value; do
 		if [[ $key == '#'* ]]; then
 			continue
@@ -53,8 +55,8 @@ lib::find_file config_file= ~/lib/capture.aliases config:capture.aliases && {
 				hosts["$current_host"]=$value
 			fi
 		fi
-	done < "$config_file" || die "could not read alias file '$config_file'"
-}
+	done < "$alias_file" || die "could not read alias file '$alias_file'"
+fi
 
 arg_host=${arg_on%%/*}
 arg_iface=${arg_on#*/}
diff --git a/bin/gmount b/bin/gmount
--- a/bin/gmount
+++ b/bin/gmount
@@ -27,10 +27,10 @@ hdd_poweroff() {
 declare -i mount
 declare -A alias outer_uuid
 
-lib::find_file config= config:{,synced/}gmount.conf.sh
+config_file=${XDG_CONFIG_HOME}/nullroute.lt/gmount.conf.sh
 
-if [[ $config ]]; then
-	. "$config" || die "could not load configuration"
+if [[ -e $config_file ]]; then
+	. "$config_file" || die "could not load configuration"
 fi
 
 # parse command line
