dropbox wrapper: add 'version', 'browse-fb'

diff --git a/bin/dropbox b/bin/dropbox
--- a/bin/dropbox
+++ b/bin/dropbox
@@ -11,6 +11,17 @@ if [ "$1" = "install" ]; then
 	echo "Downloading $url"
 	curl -L "$url" | tar xzf -
 	exit
+elif [ "$1" = "version" ]; then
+	if [ -s ~/.dropbox-dist/VERSION ]; then
+		echo "Installed: $(< ~/.dropbox-dist/VERSION)"
+		exit 0
+	else
+		echo "Not found in ~/.dropbox-dist/"
+		exit 1
+	fi
+elif [ "$1" = "browse-fb" ]; then
+	xdg-open "https://forums.dropbox.com/forum-build.php"
+	exit
 elif [ "$1" = "start" ]; then
 	cd ~
 fi
