nosymlinks: warn if the preload library is missing

diff --git a/bin/nosymlinks b/bin/nosymlinks
--- a/bin/nosymlinks
+++ b/bin/nosymlinks
@@ -4,6 +4,11 @@
 # Used as wrapper for sftp-server as many Android SFTP clients do not support symlinks correctly.
 
 objdir="${0%/*}/../obj/host.$HOSTNAME"
+lib="$objdir/unsymlink.so"
+
+if [ ! -f "$lib" ]; then
+	echo "$0: missing '$lib'" >&2
+fi
 
 export LD_PRELOAD="$objdir/unsymlink.so${LD_PRELOAD+:}$LD_PRELOAD"
 
