annex setup: rewrite

diff --git a/annex b/annex
--- a/annex
+++ b/annex
@@ -14,35 +14,30 @@ cmd=$1; shift
 case $cmd in
     setup)
         name=$1
-        [[ $name ]] \
-            || die "missing name (e.g. annex/videos)"
-        [[ $name == annex/* || $name == */annex/* ]] \
-            || die "name must contain 'annex/'"
-        [[ $name == *.git ]] \
-            || name+=".git"
-        # set up local git-annex repository
+        dir=$PWD/$name
+        if [[ ! $name ]]; then
+            die "missing name (e.g. Videos)"
+        elif [[ -d $dir ]]; then
+            die "'$dir' already exists"
+        fi
+        mkdir "$dir"
+        cd "$dir"
         if is_annex; then
-            notice "'$PWD' is already a git-annex repository"
+            die "'$PWD' is already a git-annex repository"
         elif is_git; then
             die "'$PWD' is already a non-annex Git repository"
-        else
-            log "creating a git-annex repository"
-            git init
-            git annex init
-            git annex direct
         fi
-        # set up the remote metadata repo
-        if u=$(git config remote.origin.url); then
-            notice "origin is already set up as '$u'"
-        else
-            log "creating metadata repository"
-            ssh virgule "[ -d pub/git/$name ] || git init --bare pub/git/$name"
-            log "adding origin remote"
-            git remote add origin "nullroute+ssh:$name"
+        log "setting up git-annex repository"
+        git init
+        git annex init
+        git annex direct
+        log "setting up origin repository"
+        rdir="Attic/$name.git"
+        if ! ssh virgule "[ -d $rdir ]"; then
+            ssh virgule "git init --bare $rdir && cd $rdir && git annex init"
         fi
-        git config remote.origin.annex-ignore true
-        # sync
-        log "performing initial sync"
+        log "initial sync"
+        git remote add origin "annex:${rdir%.git}"
         git annex sync
         ;;
     want-get|missing)
