miscellaneous verbosity changes

diff --git a/gettermbg b/gettermbg
--- a/gettermbg
+++ b/gettermbg
@@ -46,16 +46,16 @@ if read -r -s -d '?' -t 2 ans1 &&
 	elif [[ $ans1 == $'\e[' ]]; then
 		# No answer to color inquiry, all we got is Primary DA
 		case $1 in
-		"")		echo "gettermbg: No OSC reply from terminal" >&2; exit 1;;
+		"")		echo "${0##*/}: No OSC reply from terminal" >&2; exit 1;;
 		-l|--is-light)	false;;
 		-d|--is-dark)	true;;
 		*)		usage >&2; exit 2;;
 		esac
 	else
-		echo "gettermbg: Invalid reply from terminal: ${ans@Q}" >&2
+		echo "${0##*/}: Invalid reply from terminal: ${ans@Q}" >&2
 		exit 3
 	fi
 else
-	echo "gettermbg: Did not receive Primary DA reply from terminal" >&2
+	echo "${0##*/}: Did not receive Primary DA reply from terminal" >&2
 	exit 4
 fi
