git-import: add error messages

diff --git a/git-import b/git-import
--- a/git-import
+++ b/git-import
@@ -32,9 +32,12 @@ else
 fi
 
 cd "$dir"
+if git fast-import --quiet; then
+	if (( ! bare )); then
+		git checkout -f
+	fi
 
-git fast-import --quiet
-
-if (( ! bare )); then
-	git checkout -f
+	log "import done"
+else
+	die "import failed ($?)"
 fi
