hi: remove xdg.origin.url attr usage

diff --git a/hi b/hi
--- a/hi
+++ b/hi
@@ -150,14 +150,7 @@ fmt() {
 	}'
 }
 
-url=$(attr -qg "xdg.origin.url" "$log" 2>/dev/null) ||
-if [[ -h "$link" ]]; then
-	url=$(readlink "$link")
-elif [[ -s "$link" ]]; then
-	url=$(< "$link")
-else
-	false
-fi || die "could not find URL for $log"
+url=$(< "$link") && [[ $url ]] || die "could not find URL for $log"
 
 mkdir -p "${log%/*}" || die "cannot create cache directory"
 touch "$log"     || die "cannot create highlight cache"
