imgur: port to API v3

diff --git a/imgur b/imgur
--- a/imgur
+++ b/imgur
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # imgur script by Bart Nagel <bart@tremby.net>
-# version 3+grawity1
+# version 3+grawity2
 # I release this into the public domain. Do with it what you will.
 
 # Required: curl
@@ -25,7 +25,7 @@
 # stderr). If you have xsel or xclip the URLs will also be put on the X
 # selection, which you can usually paste with a middle click.
 
-apikey="bba16b32760b0d259092636758c9c4c2"
+API_CLIENT_ID="1d4fa0f8eeeec73" # grawity@gmail.com
 
 . lib.bash || exit
 
@@ -45,8 +45,7 @@ for file; do
 
 	curlopt=(
 		-s
-		-H "Expect: "
-		-F "key=$apikey"
+		-H "Authorization: Client-ID $API_CLIENT_ID"
 		-F "image=@$file"
 	)
 
@@ -58,30 +57,28 @@ for file; do
 		curlopt+=( "-#" )
 	fi
 
-	response=$(curl "${curlopt[@]}" \
-		http://imgur.com/api/upload.xml)
+	response=$(curl "${curlopt[@]}" https://api.imgur.com/3/upload)
 	# the "Expect: " header is to get around a problem when using this through
 	# the Squid proxy. Not sure if it's a Squid bug or what.
 
 	if (( $? )); then
 		err "upload failed (curl returned $?)"
 		continue
-	elif echo "$response" | grep -qs "<error_msg>"; then
-		err "upload failed (got error message)"
-		echo "Error message from imgur:" >&2
-		echo "$response" | sed -rn 's/.*<error_msg>(.*)<\/error_msg>.*/\1/p' >&2
+	elif [[ $response != {*} ]]; then
+		err "upload failed (non-JSON response)"
+		echo "Response from imgur:" >&2
+		echo "$response" >&2
+		continue
+	elif [[ $(echo "$response" | jq -r .success) != true ]]; then
+		echo "upload failed (API returned error)"
+		echo "Response from imgur:" >&2
+		echo "$response" >&2
 		continue
 	fi
 
-	if ! echo "$response" | grep -qs original_image; then
-		die "upload failed (probably a CAPTCHA again)"
-	fi
-
-	url=$(echo "$response" |
-		sed -rn 's/.*<original_image>(.*)<\/original_image>.*/\1/p')
-
-	deleteurl=$(echo "$response" |
-		sed -rn 's/.*<delete_page>(.*)<\/delete_page>.*/\1/p')
+	url=$(echo "$response" | jq -r .data.link)
+	deletehash=$(echo "$response" | jq -r .data.deletehash)
+	deleteurl="https://imgur.com/delete/$deletehash"
 
 	setfattr -n "user.imgur.image-url" -v "$url" "$file"
 	setfattr -n "user.imgur.delete-url" -v "$deleteurl" "$file"
