makepkg: update from pacman-git

diff --git a/makepkg b/makepkg
--- a/makepkg
+++ b/makepkg
@@ -41,7 +41,7 @@ unset CDPATH
 # Ensure GREP_OPTIONS doesn't screw with our grep calls
 unset GREP_OPTIONS
 
-declare -r makepkg_version='4.1.2'
+declare -r makepkg_version='4.1.2-490-g0d249'
 declare -r confdir='/etc'
 declare -r BUILDSCRIPT='PKGBUILD'
 declare -r startdir="$PWD"
@@ -446,7 +446,9 @@ download_bzr() {
 	local netfile=$1
 
 	local url=$(get_url "$netfile")
-	url=${url##*bzr+}
+	if [[ $url != bzr+ssh* ]]; then
+		url=${url#bzr+}
+	fi
 	url=${url%%#*}
 
 	local repo=$(get_filename "$netfile")
@@ -482,7 +484,7 @@ download_bzr() {
 		fi
 		msg2 "$(gettext "Pulling %s ...")" "${displaylocation}"
 		cd_safe "$dir"
-		if ! bzr pull "$url" --overwrite; then
+		if ! bzr pull "$url"; then
 			# only warn on failure to allow offline builds
 			warning "$(gettext "Failure while pulling %s")" "${displaylocation}"
 		fi
@@ -498,10 +500,11 @@ extract_bzr() {
 		unset fragment
 	fi
 
+	rev="last:1"
 	if [[ -n $fragment ]]; then
 		case ${fragment%%=*} in
 			revision)
-				revision=("-r" "${fragment#*=}")
+				rev="${fragment#*=}"
 				displaylocation="$url -r ${fragment#*=}"
 				;;
 			*)
@@ -516,10 +519,15 @@ extract_bzr() {
 
 	msg2 "$(gettext "Creating working copy of %s %s repo...")" "${repo}" "bzr"
 	pushd "$srcdir" &>/dev/null
-	rm -rf "${dir##*/}"
 
-	if ! { bzr checkout "$dir" "${revision[@]}" --lightweight &&
-		( cd "$repo" && bzr pull "$dir" -q --overwrite "${revision[@]}" ); }; then
+	if [[ -d "${dir##*/}" ]]; then
+		cd_safe "${dir##*/}"
+		if ! (bzr pull "$dir" -q --overwrite -r "$rev" && bzr clean-tree -q --detritus --force); then
+			error "$(gettext "Failure while updating working copy of %s %s repo")" "${repo}" "bzr"
+			plain "$(gettext "Aborting...")"
+			exit 1
+		fi
+	elif ! bzr checkout "$dir" -r "$rev"; then
 		error "$(gettext "Failure while creating working copy of %s %s repo")" "${repo}" "bzr"
 		plain "$(gettext "Aborting...")"
 		exit 1
@@ -537,7 +545,7 @@ download_git() {
 	local repo=$(get_filename "$netfile")
 
 	local url=$(get_url "$netfile")
-	url=${url##*git+}
+	url=${url#git+}
 	url=${url%%#*}
 
 	if [[ ! -d "$dir" ]] || dir_is_empty "$dir" ; then
@@ -580,9 +588,18 @@ extract_git() {
 
 	msg2 "$(gettext "Creating working copy of %s %s repo...")" "${repo}" "git"
 	pushd "$srcdir" &>/dev/null
-	rm -rf "${dir##*/}"
 
-	if ! git clone "$dir"; then
+	local updating=0
+	if [[ -d "${dir##*/}" ]]; then
+		updating=1
+		cd_safe "${dir##*/}"
+		if ! git fetch; then
+			error "$(gettext "Failure while updating working copy of %s %s repo")" "${repo}" "git"
+			plain "$(gettext "Aborting...")"
+			exit 1
+		fi
+		cd_safe "$srcdir"
+	elif ! git clone "$dir"; then
 		error "$(gettext "Failure while creating working copy of %s %s repo")" "${repo}" "git"
 		plain "$(gettext "Aborting...")"
 		exit 1
@@ -590,7 +607,7 @@ extract_git() {
 
 	cd_safe "${dir##*/}"
 
-	local ref
+	local ref=origin/HEAD
 	if [[ -n $fragment ]]; then
 		case ${fragment%%=*} in
 			commit|tag)
@@ -606,8 +623,8 @@ extract_git() {
 		esac
 	fi
 
-	if [[ -n $ref ]]; then
-		if ! git checkout -b makepkg $ref; then
+	if [[ $ref != "origin/HEAD" ]] || (( updating )) ; then
+		if ! git checkout --force --no-track -B makepkg $ref; then
 			error "$(gettext "Failure while creating working copy of %s %s repo")" "${repo}" "git"
 			plain "$(gettext "Aborting...")"
 			exit 1
@@ -626,7 +643,7 @@ download_hg() {
 	local repo=$(get_filename "$netfile")
 
 	local url=$(get_url "$netfile")
-	url=${url##*hg+}
+	url=${url#hg+}
 	url=${url%%#*}
 
 	if [[ ! -d "$dir" ]] || dir_is_empty "$dir" ; then
@@ -662,13 +679,12 @@ extract_hg() {
 
 	msg2 "$(gettext "Creating working copy of %s %s repo...")" "${repo}" "hg"
 	pushd "$srcdir" &>/dev/null
-	rm -rf "${dir##*/}"
 
-	local ref
+	local ref=tip
 	if [[ -n $fragment ]]; then
 		case ${fragment%%=*} in
 			branch|revision|tag)
-				ref=('-u' "${fragment##*=}")
+				ref="${fragment##*=}"
 				;;
 			*)
 				error "$(gettext "Unrecognized reference: %s")" "${fragment}"
@@ -677,7 +693,14 @@ extract_hg() {
 		esac
 	fi
 
-	if ! hg clone "${ref[@]}" "$dir" "${dir##*/}"; then
+	if [[ -d "${dir##*/}" ]]; then
+		cd_safe "${dir##*/}"
+		if ! (hg pull && hg update -C -r "$ref"); then
+			error "$(gettext "Failure while updating working copy of %s %s repo")" "${repo}" "hg"
+			plain "$(gettext "Aborting...")"
+			exit 1
+		fi
+	elif ! hg clone -u "$ref" "$dir" "${dir##*/}"; then
 		error "$(gettext "Failure while creating working copy of %s %s repo")" "${repo}" "hg"
 		plain "$(gettext "Aborting...")"
 		exit 1
@@ -701,47 +724,11 @@ download_svn() {
 
 	local url=$(get_url "$netfile")
 	if [[ $url != svn+ssh* ]]; then
-		url=${url##*svn+}
+		url=${url#svn+}
 	fi
 	url=${url%%#*}
 
-	if [[ ! -d "$dir" ]] || dir_is_empty "$dir" ; then
-		msg2 "$(gettext "Cloning %s %s repo...")" "${repo}" "svn"
-		mkdir -p "$dir/.makepkg"
-		if ! svn checkout --config-dir "$dir/.makepkg" "$url" "$dir"; then
-			error "$(gettext "Failure while downloading %s %s repo")" "${repo}" "svn"
-			plain "$(gettext "Aborting...")"
-			exit 1
-		fi
-	elif (( ! HOLDVER )); then
-		msg2 "$(gettext "Updating %s %s repo...")" "${repo}" "svn"
-		cd_safe "$dir"
-		if ! svn update; then
-			# only warn on failure to allow offline builds
-			warning "$(gettext "Failure while updating %s %s repo")" "${repo}" "svn"
-		fi
-	fi
-}
-
-extract_svn() {
-	local netfile=$1
-
-	local fragment=${netfile#*#}
-	if [[ $fragment = "$netfile" ]]; then
-		unset fragment
-	fi
-
-	local dir=$(get_filepath "$netfile")
-	[[ -z "$dir" ]] && dir="$SRCDEST/$(get_filename "$netfile")"
-
-	local repo=${netfile##*/}
-	repo=${repo%%#*}
-
-	msg2 "$(gettext "Creating working copy of %s %s repo...")" "${repo}" "svn"
-	pushd "$srcdir" &>/dev/null
-	rm -rf "${dir##*/}"
-
-	local ref
+	local ref=HEAD
 	if [[ -n $fragment ]]; then
 		case ${fragment%%=*} in
 			revision)
@@ -754,15 +741,38 @@ extract_svn() {
 		esac
 	fi
 
-	cp -a "$dir" .
-
-	if [[ -n ${ref} ]]; then
-		cd_safe "$(get_filename "$netfile")"
-		if ! svn update -r ${ref}; then
-			error "$(gettext "Failure while creating working copy of %s %s repo")" "${repo}" "svn"
+	if [[ ! -d "$dir" ]] || dir_is_empty "$dir" ; then
+		msg2 "$(gettext "Cloning %s %s repo...")" "${repo}" "svn"
+		mkdir -p "$dir/.makepkg"
+		if ! svn checkout -r ${ref} --config-dir "$dir/.makepkg" "$url" "$dir"; then
+			error "$(gettext "Failure while downloading %s %s repo")" "${repo}" "svn"
 			plain "$(gettext "Aborting...")"
+			exit 1
+		fi
+	elif (( ! HOLDVER )); then
+		msg2 "$(gettext "Updating %s %s repo...")" "${repo}" "svn"
+		cd_safe "$dir"
+		if ! svn update -r ${ref}; then
+			# only warn on failure to allow offline builds
+			warning "$(gettext "Failure while updating %s %s repo")" "${repo}" "svn"
 		fi
 	fi
+}
+
+extract_svn() {
+	local netfile=$1
+
+	local dir=$(get_filepath "$netfile")
+	[[ -z "$dir" ]] && dir="$SRCDEST/$(get_filename "$netfile")"
+
+	local repo=${netfile##*/}
+	repo=${repo%%#*}
+
+	msg2 "$(gettext "Creating working copy of %s %s repo...")" "${repo}" "svn"
+	pushd "$srcdir" &>/dev/null
+	rm -rf "${dir##*/}"
+
+	cp -a "$dir" .
 
 	popd &>/dev/null
 }
@@ -866,7 +876,6 @@ update_pkgver() {
 			fi
 			sed --follow-symlinks -i "s:^pkgrel=[^ ]*:pkgrel=1:" "$BUILDFILE"
 			source_safe "$BUILDFILE"
-			epoch=${epoch:-0}
 			local fullver=$(get_full_version)
 			msg "$(gettext "Updated version: %s")" "$pkgbase $fullver"
 		else
@@ -888,7 +897,7 @@ missing_source_file() {
 # return : full version spec, including epoch (if necessary), pkgver, pkgrel
 ##
 get_full_version() {
-	if [[ $epoch ]] && (( epoch > 0 )); then
+	if (( epoch > 0 )); then
 		printf "%s\n" "$epoch:$pkgver-$pkgrel"
 	else
 		printf "%s\n" "$pkgver-$pkgrel"
@@ -1309,6 +1318,8 @@ verify_integrity_sums() {
 have_sources() {
 	local a
 
+	(( ${#source[*]} )) && return 0
+
 	case $1 in
 		all)
 			for a in "${arch[@]}"; do
@@ -1316,9 +1327,7 @@ have_sources() {
 			done
 			;;
 		*)
-			if (( ${#source[*]} )) || array_build _ source_"$CARCH"; then
-				return 0
-			fi
+			array_build _ source_"$CARCH" && return 0
 			;;
 	esac
 
@@ -2031,6 +2040,100 @@ find_libprovides() {
 	printf '%s\n' "${libprovides[@]}"
 }
 
+srcinfo_open_section() {
+	printf '%s = %s\n' "$1" "$2"
+}
+
+srcinfo_close_section() {
+	echo
+}
+
+srcinfo_write_attr() {
+	# $1: attr name
+	# $2: attr values
+
+	local attrname=$1 attrvalues=("${@:2}")
+
+	# normalize whitespace, strip leading and trailing
+	attrvalues=("${attrvalues[@]//+([[:space:]])/ }")
+	attrvalues=("${attrvalues[@]#[[:space:]]}")
+	attrvalues=("${attrvalues[@]%[[:space:]]}")
+
+	printf "\t$attrname = %s\n" "${attrvalues[@]}"
+}
+
+pkgbuild_extract_to_srcinfo() {
+	# $1: pkgname
+	# $2: attr name
+	# $3: multivalued
+
+	local pkgname=$1 attrname=$2 isarray=$3 outvalue=
+
+	if pkgbuild_get_attribute "$pkgname" "$attrname" "$isarray" 'outvalue'; then
+		srcinfo_write_attr "$attrname" "${outvalue[@]}"
+	fi
+}
+
+srcinfo_write_section_details() {
+	local attr package_arch a
+	local multivalued_arch_attrs=(source provides conflicts depends replaces
+	                              optdepends makedepends checkdepends
+	                              {md5,sha{1,224,256,384,512}}sums)
+
+	for attr in "${singlevalued[@]}"; do
+		pkgbuild_extract_to_srcinfo "$1" "$attr" 0
+	done
+
+	for attr in "${multivalued[@]}"; do
+		pkgbuild_extract_to_srcinfo "$1" "$attr" 1
+	done
+
+	pkgbuild_get_attribute "$1" 'arch' 1 'package_arch'
+	for a in "${package_arch[@]}"; do
+		# 'any' is special. there's no support for, e.g. depends_any.
+		[[ $a = any ]] && continue
+
+		for attr in "${multivalued_arch_attrs[@]}"; do
+			pkgbuild_extract_to_srcinfo "$1" "${attr}_$a" 1
+		done
+	done
+}
+
+srcinfo_write_global() {
+	local singlevalued=(pkgdesc pkgver pkgrel epoch url install changelog)
+	local multivalued=(arch groups license checkdepends makedepends
+	                   depends optdepends provides conflicts replaces
+	                   noextract options backup
+	                   source {md5,sha{1,224,256,384,512}}sums)
+
+	srcinfo_open_section 'pkgbase' "${pkgbase:-$pkgname}"
+	srcinfo_write_section_details ''
+	srcinfo_close_section
+}
+
+srcinfo_write_package() {
+	local singlevalued=(pkgdesc url install changelog)
+	local multivalued=(arch groups license checkdepends depends optdepends
+	                   provides conflicts replaces options backup)
+
+	srcinfo_open_section 'pkgname' "$1"
+	srcinfo_write_section_details "$1"
+	srcinfo_close_section
+}
+
+write_srcinfo() {
+	local pkg
+
+	printf "# Generated by makepkg %s\n" "$makepkg_version"
+	printf "# %s\n" "$(LC_ALL=C date -u)"
+
+	srcinfo_write_global
+
+	for pkg in "${pkgname[@]}"; do
+		srcinfo_write_package "$pkg"
+	done
+}
+
 write_pkginfo() {
 	local builddate=$(date -u "+%s")
 	if [[ -n $PACKAGER ]]; then
@@ -2060,7 +2163,12 @@ write_pkginfo() {
 		printf "basever = %s\n" "$basever"
 	fi
 
-	printf "pkgdesc = %s\n" "${pkgdesc//+([[:space:]])/ }"
+	# TODO: all fields should have this treatment
+	local spd="${pkgdesc//+([[:space:]])/ }"
+	spd=("${spd[@]#[[:space:]]}")
+	spd=("${spd[@]%[[:space:]]}")
+
+	printf "pkgdesc = %s\n" "$spd"
 	printf "url = %s\n" "$url"
 	printf "builddate = %s\n" "$builddate"
 	printf "packager = %s\n" "$packager"
@@ -2243,6 +2351,9 @@ create_srcpackage() {
 	msg2 "$(gettext "Adding %s...")" "$BUILDSCRIPT"
 	ln -s "${BUILDFILE}" "${srclinks}/${pkgbase}/${BUILDSCRIPT}"
 
+	msg2 "$(gettext "Generating %s file...")" .SRCINFO
+	write_srcinfo > "$srclinks/$pkgbase"/.SRCINFO
+
 	local file all_sources
 
 	get_all_sources 'all_sources'
@@ -2379,13 +2490,13 @@ extract_global_var() {
 	# $2: multivalued
 	# $3: name of output var
 
-	local attr=$1 isarray=$2 outputvar=$3
+	local attr=$1 isarray=$2 outputvar=$3 ref
 
 	if (( isarray )); then
 		array_build ref "$attr"
 		[[ ${ref[@]} ]] && array_build "$outputvar" "$attr"
 	else
-		[[ -v $attr ]] && printf -v "$outputvar" %s "${!attr}"
+		[[ ${!attr} ]] && printf -v "$outputvar" %s "${!attr}"
 	fi
 }
 
@@ -3501,7 +3612,6 @@ fi
 
 # set defaults if they weren't specified in buildfile
 pkgbase=${pkgbase:-${pkgname[0]}}
-epoch=${epoch:-0}
 basever=$(get_full_version)
 
 if [[ $BUILDDIR = "$startdir" ]]; then
