nfile: add error checking

diff --git a/nfile b/nfile
--- a/nfile
+++ b/nfile
@@ -1,6 +1,8 @@
 #!/usr/bin/env bash
 # nfile – output an unique filename ("date.nnn" or "prefix – date.nnn")
 
+. lib.bash || exit
+
 prefix="$1"
 date=$(date +"%Y-%m-%d")
 mprefix="${prefix:+$prefix – }"
@@ -8,7 +10,10 @@ dir="."
 
 for (( count=0; count < 999; count++ )); do
 	printf -v name "%s%s.%03d.png" "$mprefix" "$date" "$count"
-	[[ ! -e $dir/$name && ! -e $dir/.$name.tmp ]] && break
+	if [[ ! -e $dir/$name && ! -e $dir/.$name.tmp ]]; then
+		echo "$dir/$name"
+		exit 0
+	fi
 done
 
-echo "$dir/$name"
+die "could not find an unique filename"
