nukepkg: implement --help

diff --git a/nukepkg b/nukepkg
--- a/nukepkg
+++ b/nukepkg
@@ -2,34 +2,44 @@
 
 . lib.bash || exit
 
-do:() { (PS4='+ '; set -x; "$@") }
-
-sudo:() {
-	if (( UID ))
-		then do: sudo "$@"
-		else do: "$@"
-	fi
+usage() {
+	echo "Usage: $progname [-d path] <package>..."
+	echo
+	echo "  -d <dir>      specify output directory"
 }
 
 dir=$XDG_CACHE_HOME/bacman
 
-mkdir -p "$dir" || exit
-cd "$dir"       || exit
+while getopts ":d:" OPT; do
+	case $OPT in
+	d) dir=$OPTARG;;
+	*) lib::die_getopts;;
+	esac
+done; shift $((OPTIND-1))
 
+(( $# )) || die "missing package names"
+
+log "archiving packages"
+
+mkdir -p "$dir" && cd "$dir" || exit
 for pkg; do
-	sudo: bacman "$pkg"
+	sudo: bacman "$pkg" || err "could not back up '$pkg'"
 done
 
-orphans_before=$(mktemp /tmp/nukepkg.XXXXXXXX)
-orphans_after=$(mktemp /tmp/nukepkg.XXXXXXXX)
+(( !errors )) || exit
 
+log "uninstalling packages"
+
+orphans_after=$(mktemp /tmp/nukepkg.XXXXXXXX)
 pacman -Qqdt | sort > "$orphans_before"
+
 sudo: pacman -Rn "$@"
+
+orphans_before=$(mktemp /tmp/nukepkg.XXXXXXXX)
 pacman -Qqdt | sort > "$orphans_after"
 
 new_orphans=$(comm -13 "$orphans_before" "$orphans_after")
 if [[ $new_orphans ]]; then
-	echo "New orphans: $new_orphans"
+	notice "new orphans: $new_orphans"
 fi
-
 rm -f "$orphans_before" "$orphans_after"
