onchange: actually include a bell character
Ctrl-A is not \a.

diff --git a/onchange b/onchange
--- a/onchange
+++ b/onchange
@@ -44,5 +44,5 @@ echo "Will monitor ${#paths[@]} files and run ${cmd[*]@Q}."
 inotifywait -q -m -e close_write -- "${paths[@]}" |
 	while read -r ev; do
 		echo "Event: $ev"
-		"${cmd[@]}" || warn "Command failed with status $?"
+		"${cmd[@]}" || warn "Command failed with status $?"
 	done
