pkg: let `pkg files`, `pkg stats` work on multiple packages

diff --git a/pkg b/pkg
--- a/pkg
+++ b/pkg
@@ -82,7 +82,7 @@ have pv || err "'pv' not installed"
 DBDIR="$PREFIX/pkg"
 CACHEDIR="$XDG_CACHE_HOME/pkg"
 
-name=$(basename "$PWD")
+pkgname=$(basename "$PWD")
 
 mkdir -p "$DBDIR"
 mkdir -p "$CACHEDIR/install"
@@ -97,8 +97,8 @@ configure)
 	;;
 
 install)
-	filelist="$DBDIR/$name.files"
-	tempdest="$CACHEDIR/install/$name"
+	filelist="$DBDIR/$pkgname.files"
+	tempdest="$CACHEDIR/install/$pkgname"
 
 	dist_install "$tempdest" "$@"
 
@@ -114,7 +114,7 @@ install)
 	;;
 
 uninstall|remove)
-	filelist="$DBDIR/$name.files"
+	filelist="$DBDIR/$pkgname.files"
 
 	if ! test -e "$filelist"; then
 		die "filelist $filelist not found"
@@ -146,23 +146,31 @@ ls)
 	;;
 
 files)
-	filelist="$DBDIR/$name.files"
+	(( $# )) || set -- "$pkgname"
 
-	if ! test -e "$filelist"; then
-		die "filelist $filelist not found"
-	fi
+	for pkgname; do
+		filelist="$DBDIR/$pkgname.files"
 
-	cat "$filelist"
+		if ! test -e "$filelist"; then
+			die "filelist $filelist not found"
+		fi
+
+		cat "$filelist"
+	done
 	;;
 
 stats)
-	filelist="$DBDIR/$name.files"
+	(( $# )) || set -- "$pkgname"
 
-	if ! test -e "$filelist"; then
-		die "filelist $filelist not found"
-	fi
+	for pkgname; do
+		filelist="$DBDIR/$pkgname.files"
 
-	list_stats "$filelist"
+		if ! test -e "$filelist"; then
+			die "filelist $filelist not found"
+		fi
+
+		list_stats "$filelist"
+	done
 	;;
 
 eval)
