pkg: add error checking for ls

diff --git a/pkg b/pkg
--- a/pkg
+++ b/pkg
@@ -121,6 +121,10 @@ remove)
 	;;
 
 ls|ls-files)
+	if ! test -e "$filelist"; then
+		die "filelist $filelist not found"
+	fi
+
 	cat "$filelist"
 	;;
 
