pkg: error checking for `pkg stats`

diff --git a/pkg b/pkg
--- a/pkg
+++ b/pkg
@@ -154,6 +154,10 @@ files)
 	;;
 
 stats)
+	if ! test -e "$filelist"; then
+		die "filelist $filelist not found"
+	fi
+
 	list_stats "$filelist"
 	;;
 
