pull: consistently use argsrc

diff --git a/pull b/pull
--- a/pull
+++ b/pull
@@ -91,7 +91,7 @@ do_git() {
 }
 
 do_pull() {
-	local source=$1 arg=$2
+	local argsrc=$1 arg=$2
 
 	# This function is always called with the repo as current directory.
 	local rdir=$(realpath --relative-to="$_PULL_STARTDIR" "$PWD")
@@ -102,10 +102,10 @@ do_pull() {
 	# Check cwd for supported repositories
 	if [[ -f Pullfile ]]; then
 		# Collection containing more repos
-		if [[ $source == file && $arg == . ]]; then
+		if [[ $argsrc == file && $arg == . ]]; then
 			err "Avoiding recursive descent into '$rdir' at '$PWD'"
 			return 1
-		elif [[ $source == file ]] && (( opt_dryrun > 1 )); then
+		elif [[ $argsrc == file ]] && (( opt_dryrun > 1 )); then
 			vmsg "Would descend into '$rdir'"
 			return 0
 		else
@@ -128,25 +128,25 @@ do_pull() {
 }
 
 do_main() {
-	local src=none
+	local argsrc=none
 	local errors=0
 	local -A did=()
 
 	if (( ! $# )) && [[ -s Pullfile ]]; then
 		debug "reading args from Pullfile"
-		src=file
+		argsrc=file
 		set -- $(grep '^[^#]' Pullfile)
 	fi
 
 	if (( ! $# )) && [[ -f Pullfile ]] && [[ ! -s Pullfile ]]; then
 		debug "empty Pullfile, assuming '*/'"
-		src=empty
+		argsrc=empty
 		set -- */
 	fi
 
 	if (( ! $# )); then
 		debug "no args, assuming '.'"
-		src=auto
+		argsrc=auto
 		set -- .
 	fi
 
@@ -206,7 +206,7 @@ do_main() {
 		fi
 
 		debug "- updating '$dir'"
-		(cd "$dir" && do_pull "$src" "$arg") || err "update of '$dir' failed"
+		(cd "$dir" && do_pull "$argsrc" "$arg") || err "update of '$dir' failed"
 	done
 
 	(( !errors ))
