pull: foo

diff --git a/pull b/pull
--- a/pull
+++ b/pull
@@ -8,10 +8,6 @@
 
 set -u
 
-_skip_glob=""
-skip_glob=""
-errors=0
-
 log:() {
 	"$@" || err "command '$1' failed (status $?)"
 }
@@ -90,134 +86,99 @@ do_git() {
 	fi
 }
 
-do_pull() {
-	local argsrc=$1 arg=$2
+do_pullfile() {
+	local -A skip_dirs=()
+	local skip_args=
+	local skip_glob=
+
+	if [[ -s Pullfile ]]; then
+		set -- $(grep '^[^#]' Pullfile)
+	elif [[ -e Pullfile ]]; then
+		set -- */
+	else
+		set -- .
+	fi
+
+	for arg; do
+		arg=${arg%/}
+		case $arg in
+		!*)
+			arg=${arg#!}
+			debug "Excluding glob '$arg'"
+			skip_args+="|$arg"
+			skip_glob="@(${skip_args#|})"
+			;;
+		-*)
+			arg=${arg#-}
+			arg=$(realpath "$arg")
+			debug "Excluding path '$arg'"
+			skip_dirs[$arg]=1
+			;;
+		*)
+			if [[ $skip_glob && $arg == $skip_glob ]]; then
+				debug "Skipping '$arg' (matches exclude)"
+				continue
+			fi
+			arg=$(realpath "$arg")
+			if [[ ! -d $arg ]]; then
+				warn "Skipping '$arg' (not a directory)"
+				continue
+			fi
+			if [[ ${skip_dirs[$arg]-} ]]; then
+				debug "Skipping '$arg' (path excluded)"
+				continue
+			fi
+			(cd "$arg" && main)
+			;;
+		esac
+	done
+}
+
+main() {
+	local argdepth=${argdepth:-0}
+	local rdir=
 
 	# Determine relative path for display purposes
-	local rdir=$(realpath --relative-to="$_PULL_STARTDIR" "$PWD")
+	rdir=$(realpath --relative-to="$_PULL_STARTDIR" "$PWD")
 	if [[ $rdir == . ]]; then
 		rdir=$PWD
 	fi
 
 	# Check cwd for supported repositories
 	if [[ -f Pullfile ]]; then
-		# Collection containing more repos
-		if [[ $argsrc == file && $arg == . ]]; then
-			err "Avoiding recursive descent into '$rdir' at '$PWD'"
-			return 1
-		elif [[ $argsrc == file ]] && (( opt_dryrun > 1 )); then
-			vmsg "Would descend into '$rdir'"
-			return 0
+		if (( opt_list > 1 && argdepth > 0 )); then
+			echo "$rdir"
+		elif (( opt_dryrun > 1 && argdepth > 0 )); then
+			vmsg "Would descend into '$rdir'" >&2
 		else
-			do_main
+			(let argdepth+=1; do_pullfile)
 		fi
 	elif [[ -d .git ]]; then
 		if (( opt_list )); then
 			echo "$rdir"
-			return
 		elif (( opt_dryrun )); then
-			vmsg "Would update '$rdir'"
-			return
+			vmsg "Would update '$rdir'" >&2
 		else
 			log2 "Updating '$rdir'"
-			do_git
+			do_git || err "Update failed for '$rdir'"
 		fi
 	else
-		err "No repository at '$rdir'"
+		if (( opt_dryrun )); then
+			vmsg "Would fail '$rdir'" >&2
+		else
+			log2 "Updating '$rdir'"
+			err "Not a repository: '$rdir'"
+		fi
 	fi
-}
-
-do_main() {
-	local argsrc=none
-	local errors=0
-	local -A did=()
-
-	if (( ! $# )) && [[ -s Pullfile ]]; then
-		debug "reading args from Pullfile"
-		argsrc=file
-		set -- $(grep '^[^#]' Pullfile)
-	fi
-
-	if (( ! $# )) && [[ -f Pullfile ]] && [[ ! -s Pullfile ]]; then
-		debug "empty Pullfile, assuming '*/'"
-		argsrc=empty
-		set -- */
-	fi
-
-	if (( ! $# )); then
-		debug "no args, assuming '.'"
-		argsrc=auto
-		set -- .
-	fi
-
-	for arg; do
-		debug "processing arg '$arg'"
-
-		if [[ $arg == -* ]]; then
-			arg=${arg#-}
-			if [[ ! -d $arg ]]; then
-				debug "- exclusion is not a directory, ignoring"
-				if [[ $arg == *[*?]* ]]; then
-					warn "use '!$arg', not '-$arg', to exclude globs"
-				fi
-				continue
-			fi
-			dir=$(readlink -f "$arg")
-			debug "- excluding dir '$dir'"
-			did[$dir]=y
-			continue
-		fi
-
-		if [[ $arg == !* ]]; then
-			arg=${arg#!}
-			debug "- excluding glob '$arg'"
-			_skip_glob+="|$arg"
-			skip_glob="@(${_skip_glob#|})"
-			debug "- skip_glob is now '$skip_glob'"
-			continue
-		fi
-
-		lib:trace "matching ${arg@Q} against ${skip_glob}"
-		if [[ $skip_glob && $arg == $skip_glob ]]; then
-			debug "- arg '$arg' is excluded, skipping"
-			continue
-		fi
-
-		if [[ ! -d $arg && -d $arg.git && ! ${did["$arg"]} ]]; then
-			arg+=.git
-		fi
-
-		if [[ ! -d $arg ]]; then
-			err "not a directory: '$arg'"
-			continue
-		fi
-
-		dir=$(readlink -f "$arg")
-
-		if [[ ${did[$dir]-} ]]; then
-			debug "- dir '$dir' already seen, skipping"
-			continue
-		fi
-		did[$dir]=y
-
-		if [[ -u $dir ]]; then
-			debug "- dir '$dir' is ignored (+u), skipping"
-			continue
-		fi
-
-		debug "- updating '$dir'"
-		(cd "$dir" && do_pull "$argsrc" "$arg") || err "update of '$dir' failed"
-	done
-
-	(( !errors ))
 }
 
 usage() {
 	echo "Usage: $progname [-lnt] [DIR...]"
 	echo
-	echo_opt "-l" "only list paths to be updated (implies '-n')"
-	echo_opt "-n" "dry run (parse Pullfile but don't update anything)"
-	echo_opt "-t" "immediately run 'tig' to browse commits"
+	echo_opt "-l"	"only list paths to be updated (implies '-n')"
+	echo_opt "-n"	"dry run (parse Pullfile but don't update anything)"
+	echo_opt "-nn"	"dry run (do not recurse)"
+	echo_opt "-t"	"immediately run 'tig' to browse commits"
 }
 
 # Remember original starting directory for displaying subdirs
@@ -236,4 +197,12 @@ while getopts ":lnt" OPT; do
 	esac
 done; shift $((OPTIND-1))
 
-do_main "$@" && (( !errors ))
+(( $# )) || set -- .
+
+for arg; do
+	if [[ -d $arg ]]; then
+		(cd "$arg" && main)
+	else
+		vdie "Path not a directory: $arg"
+	fi
+done
