pushover: use lib

diff --git a/pushover b/pushover
--- a/pushover
+++ b/pushover
@@ -1,11 +1,13 @@
 #!/bin/bash
+
+. lib.bash || exit
+
 title=$1
 summary=$2
 body=$3
 
 if ! [[ "$title" && "$summary" ]]; then
-	echo "error: missing title/summary" >&2
-	exit 1
+	die "missing title and/or summary"
 fi
 
 args=(-F "user=uSjWBy9oxBwZWgyJnXdPXM2eUbXnCN"
