route-zt1: support IP address as gateway

diff --git a/route-zt1 b/route-zt1
--- a/route-zt1
+++ b/route-zt1
@@ -57,12 +57,18 @@ gws4=()
 gws6=()
 
 for host in "${gateways[@]}"; do
-	fqdn=$host.zt1.nullroute.eu.org
-	gw4=$(name2addr -4 $fqdn) || die "could not resolve $fqdn for IPv4"
-	gw6=$(name2addr -6 $fqdn) || die "could not resolve $fqdn for IPv6"
-	info "resolved $host to $gw4, $gw6"
-	gws4+=("$gw4")
-	gws6+=("$gw6")
+	if [[ $host == *:* ]]; then
+		gws6+=("$host")
+	elif [[ $host == *.* ]]; then
+		gws4+=("$host")
+	else
+		fqdn=$host.zt1.nullroute.eu.org
+		gw4=$(name2addr -4 $fqdn) || die "could not resolve $fqdn for IPv4"
+		gw6=$(name2addr -6 $fqdn) || die "could not resolve $fqdn for IPv6"
+		info "resolved $host to $gw4, $gw6"
+		gws4+=("$gw4")
+		gws6+=("$gw6")
+	fi
 done
 
 args4=("${args[@]}" "${args4[@]}")
