sims3: add stuff

diff --git a/sims3 b/sims3
--- a/sims3
+++ b/sims3
@@ -1,14 +1,63 @@
-#!/bin/sh
+#!/usr/bin/env bash
+
+. lib.bash || exit
 
 C=~/.wine/drive_c
 
-#wine "$C/Program Files (x86)/Electronic Arts/The Sims 3/Game/Bin/TS3.exe"
-
-EPs=(
-	[TS3]='The Sims 3'
-	[TS3EP01]='The Sims 3 World Adventures'
+declare -A EPs=(
+    [TS3]='The Sims 3'
+    [TS3EP01]='The Sims 3 World Adventures'
 )
 
-EP='TS3EP01'
+default_EP='TS3EP01'
 
-wine "$C/Program Files (x86)/Electronic Arts/${EPs[$EP]}/Game/Bin/${EP}.exe"
+run_ep() {
+    [[ $EP && ${EPs[$EP]} ]] || die "invalid expansion pack '$EP' specified"
+
+    local EP_name=${EPs[$EP]}
+    local EP_display="\"$EP_name\" ($EP)"
+
+    debug "expansion pack $EP_display"
+
+    local dir="$C/Program Files (x86)/Electronic Arts/$EP_name"
+    local bin="$dir/Game/Bin"
+    cd "$bin"
+
+    local version=$(awk '/^GameVersion/{print $3}' skuversion.txt)
+
+    case $1 in
+        version)
+            printf "%-40s %s\n" "\"$EP_name\"" "$version"
+            ;;
+        skuversion)
+            log "$EP_display"
+            cat skuversion.txt
+            ;;
+        crack)
+            cp -v _crack/* .
+            ;;
+        uncrack)
+            cp -v _orig/* .
+            ;;
+        backup)
+            if [[ -e _orig/$EP.exe || -e _orig/TSLHost.dll ]]; then
+                confirm "backup copy already exists" || exit
+            fi
+            mkdir -p _orig
+            cp -v $EP.exe TSLHost.dll _orig/
+            ;;
+        *)
+            wine $EP.exe
+            ;;
+    esac
+}
+
+: ${EP=$default_EP}
+
+if [[ $EP == all ]]; then
+    for EP in ${!EPs[@]}; do
+        run_ep "$@"
+    done
+else
+    run_ep "$@"
+fi
