take: add error checking

diff --git a/take b/take
--- a/take
+++ b/take
@@ -1,12 +1,19 @@
 #!/usr/bin/env bash
 
+. lib.bash || exit
+
 while (( $# )); do
 	url="$1"; shift
+	debug "url: $url"
+
 	if [[ $1 && $1 != */* ]]; then
 		basename="$1"; shift
+		debug "basename overridden: $basename"
 	else
 		basename="${url##*/}"
+		debug "basename copied: $basename"
 	fi
+
 	prefix="${basename%.*} – "
 	suffix="${url##*.}"
 	date=$(date +"%Y-%m-%d")
@@ -16,7 +23,11 @@ while (( $# )); do
 		if ! [[ -e $name || -e .$name.tmp ]]; then
 			wget "$url" -O "$name"
 			fattr "$name" "origin=$url"
-			break
+			continue 2
 		fi
 	done
+
+	err "could not find a free filename for '$name'"
 done
+
+(( ! errors ))
