tan: add error checking

diff --git a/tan b/tan
--- a/tan
+++ b/tan
@@ -1,12 +1,21 @@
 #!/usr/bin/env bash
 
-root=~/.run/media/grawpqi/Private/codecard
+. lib.bash || exit
+
+media=~/.run/media/grawpqi
+root=$media/Private/codecard
 
 localpwfile=~/Private/.codecard.key
-mediapwfile=~/.run/media/grawpqi/Private/.codecard.key
+mediapwfile=$media/Private/.codecard.key
+
+test -s "$localpwfile"	|| die "local key not found: $localpwfile"
+mountpoint -q "$media"	|| die "media not mounted: $media"
+test -d "$root"		|| die "path not found: $root"
+test -s "$mediapwfile"	|| die "media key not found: $mediapwfile"
 
 decrypt() {
 	local file=$root/$1.gpg
+	test -e "$file" || die "file not found: $file"
 	cat "$file" \
 	| gpg -d --batch --passphrase-file="$localpwfile" \
 	| gpg -d --batch --passphrase-file="$mediapwfile" \
@@ -15,6 +24,7 @@ decrypt() {
 
 encrypt() {
 	local file=$root/$1.gpg
+	[ -e "$file" ] || die "file not found: $file"
 	cat \
 	| gpg -c \
 	| gpg -c --batch --passphrase-file="$mediapwfile" \
