tarball: harden against derp
$ tarball
find: cannot search `': No such file or directory
== creating archive ".tgz"
-- dumping extended attributes
/home/grawity/bin/tarball: line 15: /_attributes: Permission denied
-- archiving files
tar: Substituting `.' for empty member name
tar: : Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
1 items
touch: invalid date format ‘@’
-- archived to ".tgz"
-r--r--r-- 1 grawity grawity 45 Jun  9 15:48 .tgz
-- removing original
rm: it is dangerous to operate recursively on ‘/’
rm: use --no-preserve-root to override this failsafe
-- original directory removed

diff --git a/tarball b/tarball
--- a/tarball
+++ b/tarball
@@ -3,6 +3,8 @@
 
 . lib.bash || exit
 
+set -e
+
 case ${0##*/} in
     tarball) ext=tgz;;
     zipball) ext=zip;;
@@ -27,6 +29,12 @@ get_timestamp() {
 }
 
 dir=${1%/}
+
+if [[ ! $1 ]]; then
+	die "missing directory argument"
+elif [[ ! -d $1 ]]; then
+	die "path is not a directory"
+fi
 
 ts=$(get_timestamp "$dir")
 
