ttytter wrapper: use the system copy

diff --git a/ttytter b/ttytter
--- a/ttytter
+++ b/ttytter
@@ -1,13 +1,17 @@
 #!/usr/bin/env bash
 # wrapper for 'ttytter' (update, environ, args)
 
-EXE="$HOME/lib/ttytter"
+. lib.bash || exit
+
+#EXE="$HOME/lib/ttytter"
+EXE="/bin/ttytter"
 CONF="$XDG_CONFIG_HOME/ttytter"
 
 if [[ $1 == "update" ]]; then
-	shift
-	curl "http://www.floodgap.com/software/ttytter/ttytter.txt" > "$EXE"
-	chmod +rx "$EXE"
+	#shift
+	#curl "http://www.floodgap.com/software/ttytter/ttytter.txt" > "$EXE"
+	#chmod +rx "$EXE"
+	die "ttytter is installed system-wide, cannot update"
 fi
 
 export PATH="$HOME/bin/compat/ttytter:$PATH"
