backup: check if key exists

diff --git a/backup/backup b/backup/backup
--- a/backup/backup
+++ b/backup/backup
@@ -18,6 +18,11 @@ date=$(date +%Y%m%d)
 keyfile=$HOME/.ssh/backup_$hostname.key
 output=$backupdir/$setname/$hostname-$date.gpg
 
+if [[ ! -f $keyfile ]]; then
+	echo "error: key file $keyfile not found"
+	exit 1
+fi
+
 mkdir -p "$backupdir/$setname"
 
 ssh -aTxi "$keyfile" -o"PreferredAuthentications=publickey" "$hostname" \
