backup: read hosts & annexes from a config file

diff --git a/backup/backup b/backup/backup
--- a/backup/backup
+++ b/backup/backup
@@ -4,14 +4,28 @@
 
 progname_prefix=0
 
-bvol=/mnt/backup
+# configuration
+
+config_file=$path_config/backup.conf.sh
+
+declare -a annexes=(~/Attic/{Annex,Software,Videos,Anime})
+declare -a hosts=()
+declare -- push_volume=
+
+if [[ -f $config_file ]]; then
+	. "$config_file" || die "failed to load configuration from '$config_file'"
+else
+	warn "config file '$config_file' missing"
+fi
+
+declare -r annexes
+declare -r hosts
+declare -r push_volume
+
+# misc
+
+bvol=${push_volume:-/mnt/backup}
 conf=~/Dropbox/Apps/.config/
-annexes=(
-	~/Attic/Annex
-	~/Attic/Software
-	~/Attic/Videos
-	~/Attic/Anime
-)
 
 lock_path=
 lock_fd=
@@ -237,7 +251,7 @@ while [[ $1 ]]; do
 			homes=()
 			roots=()
 
-			for host in $(< ~/Backup/hosts.txt); do
+			for host in "${hosts[@]}"; do
 				debug "parsing host: '$host'"
 				if [[ $host == '#'* ]]; then
 					continue
