krb5db: hardcode keyid for now

diff --git a/misc/backup/krb5db-push b/misc/backup/krb5db-push
--- a/misc/backup/krb5db-push
+++ b/misc/backup/krb5db-push
@@ -2,9 +2,8 @@
 umask 077
 
 realm=$1
-keyid=$2
-if ! [[ $realm && $keyid ]]; then
-	echo "error: usage: krb5db-push <realm> <gpgkeyid>" >&2
+if ! [[ $realm ]]; then
+	echo "error: usage: krb5db-push <realm>" >&2
 	exit 1
 fi
 
@@ -13,6 +12,7 @@ if [[ -t 1 ]]; then
 	exit 1
 fi
 
+keyid="grawity@gmail.com"
 sudo kdb5_util -r "$realm" dump |
 	gpg --encrypt -r "$keyid" --batch |
 	gpg --store
