krb-pull

diff --git a/misc/backup/krb5db-push b/misc/backup/krb5db-push
--- a/misc/backup/krb5db-push
+++ b/misc/backup/krb5db-push
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
 umask 077
+
 realm=$1
 keyid=$2
-
 if ! [[ $realm && $keyid ]]; then
-	echo "error: usage: krb-push <realm> <gpgkeyid>" >&2
+	echo "error: usage: krb5db-push <realm> <gpgkeyid>" >&2
 	exit 1
 fi
 
