backup: split off

diff --git a/misc/backup/serve b/misc/backup/serve
--- a/misc/backup/serve
+++ b/misc/backup/serve
@@ -4,37 +4,38 @@ umask 077
 
 keyid="grawity@gmail.com"
 
+die() {
+	echo "$*" >&2
+	exit 1
+}
+
 encrypt() {
 	gpg --encrypt --recipient "$keyid" --batch | gpg --store -z 1
 }
 
+if [[ $SSH_ORIGINAL_COMMAND ]]; then
+	set -- $SSH_ORIGINAL_COMMAND
+	if [[ $1 == serve || $1 == */serve ]]; then
+		shift
+	else
+		die "error: incorrect arguments ('$1' != 'serve')"
+	fi
+fi
+
 setname=$1
 
 if ! [[ $setname ]]; then
-	echo "Usage: serve <setname>"
-	exit 2
+	die "Usage: serve <setname>"
 fi
 
 if [[ -t 1 ]]; then
-	echo "error: will not write to a tty"
-	exit 1
+	die "error: will not write to a tty"
 fi
 
-case "$HOSTNAME/$setname" in
-	equal/mail)
-		tar c ~/mail
-		;;
+script="$HOME/code/misc/backup/serve.$setname" "${@:2}"
 
-	equal/pub)
-		tar c ~/pub ~/lib/conf/apache2
-		;;
-
-	imaginary/dns)
-		tar c ~/lib/dns
-		;;
-
-	*/krb-NULLROUTE.EU.ORG)
-		realm=${setname#krb-}
-		sudo kdb5_util -r "$realm" dump
-		;;
-esac | encrypt
+if [[ -x $script ]]; then
+	"$script" | encrypt
+else
+	die "error: unknown set name $setname"
+fi
