update sign-kernels
The upstream repo is still at:
https://git.nullroute.lt/cgit/hacks/arch-secureboot.git/

diff --git a/system/arch/sign-kernels b/system/arch/sign-kernels
--- a/system/arch/sign-kernels
+++ b/system/arch/sign-kernels
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
-
-no:() { echo "+ ${@}"; }
-
+set -e
 shopt -s extglob
 
-efi_stub="/usr/lib/systemd/boot/efi/linuxx64.efi.stub"
-sb_cert="/etc/private/efi/DatabaseKey.crt"
-sb_key="/etc/private/efi/DatabaseKey.key"
+die() { echo "error: $*" >&1; exit 1; }
+
+efi_stub=/usr/lib/systemd/boot/efi/linuxx64.efi.stub
+sb_cert=/etc/private/efi/DatabaseKey.crt
+sb_key=/etc/private/efi/DatabaseKey.key
 in_kernels=()
 in_ucode=(/boot/intel-ucode.img)
 out_dir=/boot/EFI/Linux
@@ -17,101 +17,119 @@ if [[ $1 == @(--help|-h) ]]; then
 fi
 
 if (( UID > 0 )); then
-	echo "error: root privileges are needed" >&2
-	exit 1
+	die "Root privileges are needed"
 fi
 
 if [[ $1 == --hook ]]; then
 	while read -r line; do
 		if [[ ${line#/} == @(boot/vmlinuz*|usr/lib/modules/*/vmlinuz) ]]; then
-			echo "info: handling updated image '$line'" >&2
+			echo "Signing updated kernel image '$line'."
 			in_kernels+=("/${line#/}")
 		fi
 	done
-	shift
+elif (( $# )); then
+	in_kernels=("$@")
 fi
 
 if (( ! ${#in_kernels[@]} )); then
-	if (( $# )); then
-		in_kernels=("$@")
-	else
-		echo "info: signing all found kernel images" >&2
-		in_kernels=(/boot/vmlinuz-linux!(*.*))
-	fi
+	echo "Signing all found kernel images."
+	in_kernels=(/boot/vmlinuz-linux!(*.*))
 fi
 
-if [[ ! -e $efi_stub ]]; then
-	echo "error: bootloader stub '$efi_stub' not found" >&2
-	exit 1
+if (( ! ${#in_kernels[@]} )); then
+	die "No kernel images specified"
+elif [[ ! -e $efi_stub ]]; then
+	die "Bootloader stub '$efi_stub' not found"
 elif [[ ! -e $sb_key ]]; then
-	echo "error: Secure Boot signing key '$sb_key' not found" >&2
-	exit 1
+	die "Secure Boot signing key '$sb_key' not found"
 elif [[ ! -e $sb_cert ]]; then
-	echo "error: Secure Boot signing certificate '$sb_key' not found" >&2
-	exit 1
+	die "Secure Boot signing certificate '$sb_key' not found"
 fi
 
-mkdir -p "$out_dir" || exit
+mkdir -p "$out_dir"
 
 for in_vmlinuz in "${in_kernels[@]}"; do
-	if [[ ! -e $in_vmlinuz ]]; then
-		echo "error: kernel image '$in_vmlinuz' not found" >&2
-		exit 1
-	elif [[ $in_vmlinuz == /usr/lib/modules/*/vmlinuz ]]; then
-		package=$(< "${in_vmlinuz%/*}/pkgbase")
-	elif [[ $in_vmlinuz == /boot/vmlinuz-* ]]; then
-		package=${in_vmlinuz##*/vmlinuz-}
-	else
-		echo "error: could not determine package name for '$in_vmlinuz'" >&2
-		exit 1
+	if [[ ! -s $in_vmlinuz ]]; then
+		die "Kernel image '$in_vmlinuz' not found"
 	fi
 
-	os_name="$(. /etc/os-release && echo "$PRETTY_NAME")" || exit
-	os_version="$(expac %v "$package")"
-	os_release=(
-		PRETTY_NAME	"$os_name"
-		ID		"linux"
-		VERSION_ID	"${os_version}-signed"
-	)
-	echo "[$package] found $in_vmlinuz, version $os_version"
+	# Try to guess the pkg_name without invoking a slow `pacman -Qo`
+	case $in_vmlinuz in
+		/usr/lib/modules/*/vmlinuz)
+			pkg_name=$(< "${in_vmlinuz%/*}/pkgbase");;
+		/boot/vmlinuz-*)
+			pkg_name=${in_vmlinuz##*/vmlinuz-};;
+		*)
+			die "Could not determine pkg_name name for '$in_vmlinuz'";;
+	esac
+	pkg_version=$(expac %v "$pkg_name")
+	echo "Found kernel image $in_vmlinuz, version $pkg_version ($pkg_name)"
 
-	cmdline=$(grep '^[^#]' /etc/kernel/cmdline | tr -s '\n' ' ') || exit
-	in_initrd="/boot/initramfs-$package.img"
-	in_initrds=("${in_ucode[@]}" "$in_initrd")
-	out_image="$out_dir/vmlinuz-$package.efi"
+	# .initrd
+	in_initrd="/boot/initramfs-${pkg_name}.img"
 	if [[ ! -s $in_initrd ]]; then
-		echo "error: could not find initramfs '$in_initrd'" >&2
-		exit 1
+		die "Initramfs archive '$in_initrd' not found for this kernel"
 	fi
+	in_initrds=("${in_ucode[@]}" "$in_initrd")
 
-	# Put temporary files where space is plentiful, as osslsigncode silently eats -ENOSPC
-	tmp_raw_image=$(mktemp /tmp/vmlinuzXXXXXXXX)
-	tmp_signed_image=$(mktemp /tmp/vmlinuzXXXXXXXX)
+	# .cmdline
+	cmdline=$(grep '^[^#]' /etc/kernel/cmdline | tr -s '\n' ' ')
 
-	copy_args=(
-		--add-section		.osrel=<(printf '%s="%s"\n' "${os_release[@]}")
-		--change-section-vma	.osrel=0x20000
-		--add-section		.cmdline=<(printf '%s' "$cmdline")
-		--change-section-vma	.cmdline=0x30000
-		--add-section		.linux="$in_vmlinuz"
-		--change-section-vma	.linux=0x2000000
-		--add-section		.initrd=<(cat "${in_initrds[@]}")
-		--change-section-vma	.initrd=0x3000000
+	# .osrel
+	os_id=$(. /etc/os-release && echo "$ID")
+	os_name=$(. /etc/os-release && echo "$PRETTY_NAME")
+	os_release=(
+		ID		"$os_id"
+		PRETTY_NAME	"$os_name"
+		VERSION_ID	"${pkg_version}-signed"
 	)
 
-	echo "[$package] generating bundle from '$in_vmlinuz'"
-	objcopy "${copy_args[@]}" "$efi_stub" "$tmp_raw_image" || exit
+	# Put temporary files where space is plentiful, as osslsigncode
+	# silently eats -ENOSPC.
+	tmp_dir=$(mktemp -d /tmp/sign-kernels.XXXXXXXX)
+	tmp_raw_image=$tmp_dir/bundle_raw.efi
+	tmp_signed_image=$tmp_dir/bundle_signed.efi
 
-	sbsign_args=(--cert "$sb_cert" --key "$sb_key")
-	ossl_args=(-certs "$sb_cert" -key "$sb_key" -h sha256 -verbose)
+	echo " - Generating image..."
+	objcopy \
+		--add-section		.osrel=<(printf '%s="%s"\n' "${os_release[@]}") \
+		--change-section-vma	.osrel=0x20000 \
+		--add-section		.cmdline=<(printf '%s' "$cmdline") \
+		--change-section-vma	.cmdline=0x30000 \
+		--add-section		.splash=/usr/share/systemd/bootctl/splash-arch.bmp \
+		--change-section-vma	.splash=0x40000 \
+		--add-section		.linux="$in_vmlinuz" \
+		--change-section-vma	.linux=0x2000000 \
+		--add-section		.initrd=<(cat "${in_initrds[@]}") \
+		--change-section-vma	.initrd=0x3000000 \
+		"$efi_stub" "$tmp_raw_image"
 
-	echo "[$package] signing with key '$sb_key'"
-	#sbsign "${sbsign_args[@]}" --output "$tmp_signed_image" "$tmp_raw_image" || exit
-	osslsigncode sign "${ossl_args[@]}" -in "$tmp_raw_image" -out "$tmp_signed_image" || exit
+	echo " - Signing bundle (with key $sb_key)..."
+	#sbsign \
+	#	--cert "$sb_cert" \
+	#	--key "$sb_key" \
+	#	--output "$tmp_signed_image" \
+	#	"$tmp_raw_image"
+	osslsigncode sign \
+		-certs "$sb_cert" \
+		-key "$sb_key" \
+		-h sha256 \
+		-in "$tmp_raw_image" \
+		-out "$tmp_signed_image" \
+		> /dev/null
 
-	echo "[$package] installing as '$out_image'"
-	rm -f "$tmp_raw_image"
-	mv -b "$tmp_signed_image" "$out_image" || exit
-	sync "$out_image" || exit
+	# Atomically replace the old image with the new one (as far as FAT32
+	# allows), and make sure it's flushed to disk in case we're running
+	# with root=/bin/sh.
+	case $pkg_name in
+		linux)	out_image="$out_dir/$os_id.efi";;
+		*)	out_image="$out_dir/$os_id-${pkg_name#linux-}.efi";;
+	esac
+	mv "$tmp_signed_image" "${out_image}.new"
+	sync "${out_image}.new"
+	mv -b "${out_image}.new" "$out_image"
+	sync "$out_image"
 	rm -f "$out_image~"
+	rm -rf "$tmp_dir"
+	echo " - Image $out_image built."
 done
