gencommit: might as well admit that this is a bash script

diff --git a/security/gencommit b/security/gencommit
--- a/security/gencommit
+++ b/security/gencommit
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env bash
 # gencommit -- committed identity generator
 #   (see http://en.wikipedia.org/wiki/Wikipedia:CID for explanation)
 #
@@ -16,12 +16,12 @@
 #
 #     commitment = public + " " + domain + " " + date + " " + hashfunc
 
+. lib.bash || exit
+
 fmtseed() { printf '%s %s %s' "$@"; }
 unfmtdate() { date -d "$1" +'%s'; }
 fmtdate() { date -d "$1" +'%Y-%m-%d'; }
 fmthashfunc() { printf '%s' "$1" | tr 'A-Z' 'a-z' | tr -d -c 'a-z0-9'; }
-
-stop() { echo "$*" >&2; exit 1; }
 
 colwidth=11
 
@@ -57,8 +57,7 @@ hash=$3
 hash=$(fmthashfunc "${hash:-sha1}")
 
 if [[ ! "${fhash[hash]}" ]]; then
-	echo "Unsupported hash '$hash'" >&2
-	exit 1
+	die "unsupported hash '$hash'"
 fi
 
 if [[ "$domain" ]]; then
@@ -68,7 +67,7 @@ else
 fi
 
 if ! [[ "$domain" ]]; then
-	stop "Domain is empty."
+	die "domain is empty"
 fi
 
 if [[ "$date" ]]; then
@@ -80,7 +79,7 @@ else
 fi
 
 if ! [[ "$date" ]]; then
-	stop "Invalid date."
+	die "invalid date '$date'"
 fi
 
 if (( $(unfmtdate "$date") < $(unfmtdate "2013-11-15") )); then
@@ -92,7 +91,7 @@ fi
 readp "passphrase?" passphrase
 
 if ! [[ "$passphrase" ]]; then
-	stop "Passphrase is empty."
+	die "passphrase is empty"
 fi
 
 # generate the site secret that might be revealed to admins
