pkinit: avoid breakage when no $DISPLAY

diff --git a/kerberos/pkinit b/kerberos/pkinit
--- a/kerberos/pkinit
+++ b/kerberos/pkinit
@@ -13,12 +13,22 @@ X509_IDENTITY="FILE:$HOME/.pki/private/pkinit#$princ.pem"
 err="Internal error"
 nm-online -qt 600
 {
-	ecryptfs-mount-x11 && {
+	if [[ $DISPLAY ]]; then
+		ecryptfs-mount-x11
+	else
+		mountpoint -q ~/Private
+	fi && {
 		err=$(kinit -X X509_user_identity="$X509_IDENTITY" "$princ" <<< "X" 2>&1)
 	} <<< "bogus"
-} || exec notify \
-	-s '+pkinit' \
-	-A \
-	-i error \
-	"Kerberos login failed" \
-	"$err"
+} || if [[ $DISPLAY ]]; then
+	notify \
+		-s '+pkinit' \
+		-A \
+		-i error \
+		"Kerberos login failed" \
+		"$err"
+	exit 1
+else
+	echo "Kerberos login failed: $err" >&2
+	exit 1
+fi
