bootstrap: fix crontab check

diff --git a/dist/bootstrap b/dist/bootstrap
--- a/dist/bootstrap
+++ b/dist/bootstrap
@@ -104,11 +104,15 @@ if [[ ! -s ~/.k5login ]] && [[ -f /etc/krb5.keytab ]]; then
 	dist/update-k5login &
 fi
 
-if crontab -l >/dev/null && ! { crontab -l 2>/dev/null |
-		grep -Eqs "[[:space:]]ID=pull[[:space:]]|code/dist/pull"; }; then
-	log "adding dist/pull to crontab"
-	(crontab -l 2>/dev/null || true;
-		echo -e '@daily\tID=pull\t~/code/dist/pull') | crontab -
+if err=$(crontab -l 2>&1 >/dev/null) || [[ $err == "no crontab for $USER" ]]; then
+	if ! crontab -l 2>/dev/null |
+		grep -Eqs "[[:space:]]ID=pull[[:space:]]|code/dist/pull"; then
+		log "adding dist/pull to crontab"
+		(crontab -l 2>/dev/null || true;
+			echo -e '@daily\tID=pull\t~/code/dist/pull') | crontab -
+	fi
+else
+	warn "unable to add dist/pull to crontab: '$err'"
 fi
 
 if ! { have mailx && fgrep -qs NAILRC "$(which mailx)"; } &&
@@ -124,7 +128,6 @@ elif [[ -s ~/.forward ]]; then
 else
 	log "forwarding mail to $mail"
 	echo "$mail" > ~/.forward
-
 	log "sending a test email"
 	echo "Test email from $USER($UID) at $FQDN" \
 		| mailx -s "Test from $HOSTNAME" "$mail"
