dist/bootstrap: clarify error message

diff --git a/dist/bootstrap b/dist/bootstrap
--- a/dist/bootstrap
+++ b/dist/bootstrap
@@ -46,8 +46,8 @@ for bin in ${wants[@]}; do
 	esac
 done
 
-(( errors ))   && exit 1
-(( warnings )) && { confirm "continue with setup?" || exit 1; }
+(( errors ))   && { err "required tools missing";    exit 1; }
+(( warnings )) && { confirm "continue bootstrap?" || exit 1; }
 
 # set up dotfiles
 
