Snapshot

diff --git a/dist/bootstrap b/dist/bootstrap
--- a/dist/bootstrap
+++ b/dist/bootstrap
@@ -1,59 +1,54 @@
 #!/usr/bin/env bash
-mail=grawity@gmail.com
 
 have() { command -v "$1" >/dev/null; }
 
-log() { printf "\e[32m=\e[m %s\e[m\n" "$*"; }
+log() { printf "\033[32m=\033[m %s\033[m\n" "$*"; }
 
-log_ok() { printf "\e[34m=\e[m %s\e[m\n" "$*"; }
+warn() { printf "\033[1;33mwarning:\033[m %s\033[m\n" "$*"; ((++warnings)); }
 
-warn() { printf "\e[1;33mwarning:\e[m %s\e[m\n" "$*"; ((++warnings)); }
-
-err() { printf "\e[1;31merror:\e[m %s\e[m\n" "$*"; ((++errors)); false; }
-
-die() { err "$@"; exit 1; }
+err() { printf "\033[1;31merror:\033[m %s\033[m\n" "$*"; ! ((++errors)); }
 
 confirm() {
-	local msg=$1 ans=
-	read -ep $'\001\e[1;36m\002(?)\001\e[m\002'" $msg " -t 10 ans && [[ $ans == y ]]
+	printf "\033[1;36m(?)\033[m %s " "$*"
+	read -t 10 REPLY &&
+	[[ $REPLY == 'y' ]]
 }
 
 check-gpg-version() {
-	local version major minor rest
-	version=$($GPG --version | sed 's/gpg (GnuPG) //; q')
-	IFS="." read -r major minor rest <<< "$version"
-	(( major >= 2 )) || (( major == 1 && minor >= 4 ))
+	$GPG --version | sed 's/gpg (GnuPG) //; q' | {
+		IFS="." read -r major minor rest
+		(( major >= 2 )) || (( major == 1 && minor >= 4 ))
+	}
 }
 
 # check for necessary programs
 
-export -f have
+EMAIL=grawity@gmail.com
+
+cd ~/code
+
 errors=0
 warnings=0
 
-PATH=~/code/bin:$PATH
-cd ~/code
-
-have gmake && MAKE=${MAKE:-gmake}
-MAKE=${MAKE:-make}
-
-have gpg2 && GPG=${GPG:-gpg2}
-GPG=${GPG:-gpg}
+if have gpg2; then
+	GPG=gpg2
+else
+	GPG=gpg
+fi
 
 wants=(
 	crontab
 	!curl
 	gcc
 	!git
-	!$GPG
+	$GPG
 	mailx
-	!$MAKE
-	perl
+	!perl
 )
 
-for bin in "${wants[@]}"; do
+for bin in ${wants[@]}; do
 	case $bin in
-	!*)	bin=${bin#!};
+	!*)	bin=${bin#!}
 		have "$bin" || err  "$bin not installed";;
 	*)	have "$bin" || warn "$bin not installed";;
 	esac
@@ -63,50 +58,36 @@ done
 ((warnings)) && { confirm "continue with setup?" || exit 1; }
 warnings=0
 
-# determine our FQDN
-
-if have perl; then
-	FQDN=$(fqdn)
-elif have getent && f=$(getent hosts "$HOSTNAME" 2>/dev/null); then
-	read _ FQDN _ <<< "$f"
-elif have hostname && f=$(hostname -f 2>/dev/null); then
-	FQDN=$f
-else
-	FQDN=$HOSTNAME
-fi
-
-# compile tools
-
-if ! $MAKE -q; then
-	log "building tools"
-	$MAKE
-fi
+FQDN=$(bin/fqdn)
 
 # set up dotfiles
 
-if [[ ! -d ~/lib/dotfiles/.git ]]; then
-	log "cloning dotfiles.git"
-	mkdir -p ~/lib
-	git clone "git://github.com/grawity/dotfiles.git" \
-		~/lib/dotfiles
+if [ ! -d ~/bin ]; then
+	mkdir -p ~/bin
 fi
 
-if [[ -z $PREFIX ]]; then
-	log "symlinking dotfiles"
+if [ ! -d ~/lib/dotfiles ]; then
+	log "cloning dotfiles.git"
+	mkdir -p ~/lib
+	git clone "git://github.com/grawity/dotfiles.git" ~/lib/dotfiles
+fi
+
+if [ ! "$PREFIX" ]; then
+	log "installing dotfiles"
 	(cd ~/lib/dotfiles && ./install)
 	. ~/.profile
 fi
 
 # fix location of ~/.local/man
 
-if [[ -L $PREFIX/man ]]; then
+if [ -L "$PREFIX/man" ]; then
 	rm -f "$PREFIX/man"
 	mkdir -p "$PREFIX/man"
 fi
 
-if [[ -L $PREFIX/share/man ]]; then
+if [ -L "$PREFIX/share/man" ]; then
 	true
-elif [[ -d $PREFIX/share/man ]]; then
+elif [ -d "$PREFIX/share/man" ]; then
 	log "moving manual pages"
 	cp -alf "$PREFIX/share/man" "$PREFIX/"
 	rm -rf "$PREFIX/share/man" "$PREFIX/man/index.db"
@@ -118,35 +99,31 @@ fi
 
 # install NullCA
 
-if [[ ! -f ~/.pki/ca/nullroute.pem ]]; then
-	log "installing Nullroute CA certificate"
-	mkdir -p -m 0700 ~/.pki/ca
-	cp dist/nullroute.pem ~/.pki/ca/
-	have c_rehash && c_rehash ~/.pki/ca/ >/dev/null &
+if [ ! -f ~/.pki/ca/nullroute.pem ]; then
+	log "installing CA certificates"
+	install -dm0644 dist/nullroute.pem ~/.pki/ca/nullroute.pem
+	if have c_rehash; then
+		c_rehash ~/.pki/ca/ >/dev/null &
+	fi
 fi
 
 # set up authorized_keys
 
-if [[ ! -s ~/.ssh/authorized_keys ]]; then
-	if have $GPG && check-gpg-version; then
-		log "enabling SSH key updates"
-		security/update-authorized-keys -r
+if [ ! -s ~/.ssh/authorized_keys ]; then
+	if ! have $GPG; then
+		warn "skipping sshupdate: 'gpg' missing"
+	elif ! check-gpg-version; then
+		warn "skipping sshupdate: 'gpg' too old"
 	else
-		warn "unable to auto-update authorized_keys; gpg missing or too old"
+		log "configuring sshupdate"
+		security/update-authorized-keys -r
 	fi
-fi
-
-# set up k5login
-
-if [[ ! -s ~/.k5login ]] && [[ -f /etc/krb5.keytab ]]; then
-	log "creating ~/.k5login"
-	security/update-k5login &
 fi
 
 # set up dist/pull
 
 if ! have crontab; then
-	warn "not adding dist/pull: \`crontab\` missing"
+	warn "not adding dist/pull: 'crontab' missing"
 elif err=$(crontab -l 2>&1 >/dev/null) || [[ $err == "no crontab for $USER" ]]; then
 	if ! crontab -l 2>/dev/null |
 		grep -Eqs "[[:space:]]ID=pull[[:space:]]|code/dist/pull"; then
@@ -158,32 +135,48 @@ else
 	warn "unable to add dist/pull to crontab: '$err'"
 fi
 
-if ! { have mailx && fgrep -qs NAILRC "$(which mailx)"; } &&
-confirm "heirloom-mailx missing, install?"; then
-	log "installing heirloom-mailx"
-	dist/install-mailx.sh
+if ! { have mailx && fgrep -qs NAILRC "$(which mailx)"; }; then
+	confirm "heirloom-mailx missing, install?" && {
+		log "installing heirloom-mailx"
+		dist/install-mailx.sh
+	}
 fi
 
-if [[ $FQDN == "equal.cluenet.org" ]]; then
-	log_ok "skipping ~/.forward on the mail server"
-elif [[ -s ~/.forward ]]; then
-	log_ok "mail is being forwarded to $(sed 1q ~/.forward)"
+if [ "$HOSTNAME" == "equal" ]; then
+	log "skipping .forward on this server"
+elif [ -s ~/.forward ]; then
+	log "mail is forwarded to $(sed 1q ~/.forward)"
 else
-	log "forwarding mail to $mail"
-	echo "$mail" > ~/.forward
-	if have mailx; then
-		log "sending a test email"
-		echo "Test email from $USER($UID) at $FQDN" \
-			| mailx -s "Test from $HOSTNAME" "$mail"
+	log "forwarding mail to $EMAIL"
+	echo "$EMAIL" > ~/.forward
+
+	if have /usr/lib/sendmail; then
+		SENDMAIL=/usr/lib/sendmail
+	elif have /usr/sbin/sendmail; then
+		SENDMAIL=/usr/sbin/sendmail
 	else
-		warn "skipping test email: \`mailx\` missing"
+		SENDMAIL=sendmail
+	fi
+
+	if have $SENDMAIL; then
+		log "sending a test mail"
+		{
+		echo "Subject: Test from $HOSTNAME"
+		echo "Date: $(date "+%a, %d %b %Y %H:%M:%S %z")"
+		echo "To: <$EMAIL>"
+		echo ""
+		echo "Test mail from $USER($UID) at $FQDN"
+		} | $SENDMAIL -i "$EMAIL"
+	else
+		warn "'sendmail' missing, skipping test mail"
 	fi
 fi
 
-if have perl && ! have cpanm &&
-confirm "cpanminus missing, install?"; then
-	log "Installing cpanminus"
-	curl -L http://cpanmin.us | perl - --self-upgrade
+if have perl && ! have cpanm; then
+	confirm "cpanminus missing, install?" && {
+		log "installing cpanminus"
+		curl -Lk http://cpanmin.us | perl - --self-upgrade
+	}
 fi
 
 wait
