git up: warn if it's a svn clone

diff --git a/devel/git-up b/devel/git-up
--- a/devel/git-up
+++ b/devel/git-up
@@ -24,6 +24,11 @@ git_up_here() {
 		return 1
 	fi
 
+	if [ -e .git/svn ]; then
+		echo "error: '$PWD' is a Git SVN clone; not implemented yet" >&2
+		return 1
+	fi
+
 	old=$(git rev-parse "HEAD")
 	git fetch
 	if [ "$(git rev-parse --is-bare-repository)" != "true" ]; then
@@ -44,6 +49,8 @@ git_up_here() {
 
 (( $# )) || set -- "."
 
+err=0
 for repo in "$@"; do
-	(cd "$repo" && git_up_here)
+	(cd "$repo" && git_up_here) || err=1
 done
+exit $err
