mklinux: use bash

diff --git a/devel/mklinux b/devel/mklinux
--- a/devel/mklinux
+++ b/devel/mklinux
@@ -1,5 +1,12 @@
-#!/bin/sh -e
+#!/usr/bin/env bash
 # mklinux – script to compile and install a Linux kernel for my laptop
+
+set -e
+
+. lib.bash || exit
+
+progname='mklinux'
+progname_prefix=0
 
 log() { printf '\e[1;36m*\e[m \e[36m%s\e[m\n' "$*";
 	case $TERM in xterm*)
@@ -102,6 +109,7 @@ for mod in ${emods[@]}; do
 		echo "done."
 	else
 		echo "failed."
+		warn "build failed for $mod"
 	fi
 done
 
