devel/pull: realize that $# is never going to be 0 at this point

diff --git a/devel/pull b/devel/pull
--- a/devel/pull
+++ b/devel/pull
@@ -180,6 +180,7 @@ do_pull() {
 do_main() {
 	debug "main[$[++depth],$BASHPID] called, checking for Pullfile"
 	local errors=0
+	local -A did
 
 	if [[ ! $_PULL_STARTDIR ]]; then
 		export _PULL_STARTDIR=$PWD
@@ -196,68 +197,64 @@ do_main() {
 	fi
 
 	if (( ! $# )); then
+		debug "no args, assuming '.'"
 		set -- .
 	fi
 
-	if (( $# )); then
-		declare -A did
-		for arg; do
-			debug "processing arg '$arg'"
+	for arg; do
+		debug "processing arg '$arg'"
 
-			if [[ $arg == -* ]]; then
-				arg=${arg#-}
-				if [[ ! -d $arg ]]; then
-					debug "- exclusion is not a directory, ignoring"
-					continue
-				fi
-				dir=$(readlink -f "$arg")
-				debug "- excluding dir '$dir'"
-				did[$dir]=y
-				continue
-			fi
-
-			if [[ $arg == !* ]]; then
-				arg=${arg#!}
-				debug "- excluding glob '$arg'"
-				_skip_glob+="|$arg"
-				skip_glob="@(${_skip_glob#|})"
-				debug "- skip_glob is now '$skip_glob'"
-				continue
-			fi
-
-			if [[ $skip_glob && $arg == $skip_glob ]]; then
-				debug "- arg '$arg' is excluded, skipping"
-				continue
-			fi
-
-			if [[ ! -d $arg && -d $arg.git ]]; then
-				arg+=.git
-			fi
-
+		if [[ $arg == -* ]]; then
+			arg=${arg#-}
 			if [[ ! -d $arg ]]; then
-				err "not a directory: '$arg'"
+				debug "- exclusion is not a directory, ignoring"
 				continue
 			fi
-
 			dir=$(readlink -f "$arg")
-
-			if [[ ${did[$dir]} ]]; then
-				debug "- dir '$dir' already seen, skipping"
-				continue
-			fi
+			debug "- excluding dir '$dir'"
 			did[$dir]=y
+			continue
+		fi
 
-			if is_ignored "$dir"; then
-				debug "- dir '$dir' is ignored (+u), skipping"
-				continue
-			fi
+		if [[ $arg == !* ]]; then
+			arg=${arg#!}
+			debug "- excluding glob '$arg'"
+			_skip_glob+="|$arg"
+			skip_glob="@(${_skip_glob#|})"
+			debug "- skip_glob is now '$skip_glob'"
+			continue
+		fi
 
-			debug "- updating '$dir'"
-			(cd "$dir" && do_pull) || err "update of '$dir' failed"
-		done
-	else
-		do_pull || err "update of . failed"
-	fi || (( ++errors ))
+		if [[ $skip_glob && $arg == $skip_glob ]]; then
+			debug "- arg '$arg' is excluded, skipping"
+			continue
+		fi
+
+		if [[ ! -d $arg && -d $arg.git ]]; then
+			arg+=.git
+		fi
+
+		if [[ ! -d $arg ]]; then
+			err "not a directory: '$arg'"
+			continue
+		fi
+
+		dir=$(readlink -f "$arg")
+
+		if [[ ${did[$dir]} ]]; then
+			debug "- dir '$dir' already seen, skipping"
+			continue
+		fi
+		did[$dir]=y
+
+		if is_ignored "$dir"; then
+			debug "- dir '$dir' is ignored (+u), skipping"
+			continue
+		fi
+
+		debug "- updating '$dir'"
+		(cd "$dir" && do_pull) || err "update of '$dir' failed"
+	done
 
 	debug "main[$depth,$BASHPID] returning with ${errors:-0} errors"
 	(( !errors ))
