devel/pull: propagate failures

diff --git a/devel/pull b/devel/pull
--- a/devel/pull
+++ b/devel/pull
@@ -18,7 +18,7 @@ is() {
 
 log:() {
 	lib::msg "$*" 'logcmd'
-	"$@"
+	"$@" || err "command '$1' failed (status $?)"
 }
 
 upd:() {
@@ -167,6 +167,7 @@ do_pull() {
 	else
 		is none
 	fi
+	(( !errors ))
 }
 
 do_main() {
@@ -237,7 +238,7 @@ do_main() {
 
 			debug "- updating '$dir'"
 			did[$dir]=y
-			(cd "$dir" && ! is_ignored && do_pull)
+			(cd "$dir" && { is_ignored || do_pull; })
 		done
 	else
 		do_pull
@@ -253,6 +254,4 @@ while getopts ":n" OPT; do
 	esac
 done; shift $((OPTIND-1))
 
-do_main "$@"
-
-(( !errors ))
+do_main "$@" && (( !errors ))
