devel/pull: allow Pullfile to contain . for current directory

diff --git a/devel/pull b/devel/pull
--- a/devel/pull
+++ b/devel/pull
@@ -56,7 +56,7 @@ do_pull() {
 
 	if (( opt_dryrun > 1 )); then
 		is "noop"
-	elif [[ -f Pullfile ]]; then
+	elif [[ -f Pullfile ]] && ! [[ $1 == file && $2 == . ]]; then
 		do_main
 	elif (( opt_dryrun > 0 )); then
 		is "noop"
@@ -171,6 +171,7 @@ do_pull() {
 do_main() {
 	debug "main[$[++depth],$BASHPID] called, checking for Pullfile"
 
+	local src=none
 	local errors=0
 	local -A did
 
@@ -180,16 +181,19 @@ do_main() {
 
 	if (( ! $# )) && [[ -s Pullfile ]]; then
 		debug "reading args from Pullfile"
+		src=file
 		set -- $(grep '^[^#]' Pullfile)
 	fi
 
 	if (( ! $# )) && [[ -f Pullfile ]] && [[ ! -s Pullfile ]]; then
 		debug "empty Pullfile, assuming '*/'"
+		src=empty
 		set -- */
 	fi
 
 	if (( ! $# )); then
 		debug "no args, assuming '.'"
+		src=auto
 		set -- .
 	fi
 
@@ -248,7 +252,7 @@ do_main() {
 		fi
 
 		debug "- updating '$dir'"
-		(cd "$dir" && do_pull) || err "update of '$dir' failed"
+		(cd "$dir" && do_pull "$src" "$arg") || err "update of '$dir' failed"
 	done
 
 	if (( errors && depth == 1 )); then
