sprunge: warn about empty/nonexistent files

diff --git a/net/sprunge b/net/sprunge
--- a/net/sprunge
+++ b/net/sprunge
@@ -48,6 +48,7 @@ post() {
 
 cache=${XDG_CACHE_HOME:-$HOME/.cache}/sprunge
 
+err=0
 umask 077
 
 if [ ! "$1" ] || [ "$1" = "-" ]; then
@@ -78,12 +79,26 @@ if [ ! "$1" ] || [ "$1" = "-" ]; then
 			rm -f "$file"
 		fi
 	else
-		echo "stdin empty" >&2
+		echo "stdin: empty" >&2
+		err=1
 		rm -f "$file"
 	fi
 else
 	for file; do
-		echo -n "$file → "
-		post "$file"
+		if [ ! -f "$file" ]; then
+			echo "$file: not a file" >&2
+			err=1
+		elif [ -s "$file" ]; then
+			echo -n "$file → "
+			post "$file"
+		elif [ -e "$file" ]; then
+			echo "$file: empty" >&2
+			err=1
+		else
+			echo "$file: not found" >&2
+			err=1
+		fi
 	done
 fi
+
+exit $err
