sprunge: save the URL as an xattr

diff --git a/net/sprunge b/net/sprunge
--- a/net/sprunge
+++ b/net/sprunge
@@ -1,8 +1,18 @@
 #!/bin/sh -e
 # Simple sprunge.us pastebin client
 
+seturl() {
+	setfattr -n "user.sprunge-url" -v "$2" "$1" || :
+} 2>/dev/null
+
 post() {
-	curl -sF "sprunge=<$1" http://sprunge.us/
+	local url=$(curl -sF "sprunge=<$1" http://sprunge.us/)
+	if [ "$url" ]; then
+		seturl "$1" $url
+		echo $url
+	else
+		echo "...failed"
+	fi
 }
 
 if [ -z "$1" ]; then
