testrad: do not require 'radtest' if we only do EAP tests

diff --git a/net/testrad b/net/testrad
--- a/net/testrad
+++ b/net/testrad
@@ -306,9 +306,6 @@ fi
 
 # check for necessary tools
 
-have 'radtest' ||
-	err "missing 'radtest' binary"
-
 have "$eapol_bin" ||
 	err "missing '$eapol_bin' binary"
 
@@ -616,6 +613,8 @@ else
 	if (( dump_config )); then
 		notice "dumping generated config and exiting"
 		cmd=(: "${cmd[@]}")
+	else
+		have "${cmd[0]}" || die "missing '${cmd[0]}' binary"
 	fi
 fi
 
