testrad: automatically look in synced/ for the config

diff --git a/net/testrad b/net/testrad
--- a/net/testrad
+++ b/net/testrad
@@ -166,9 +166,11 @@ eapol_bin="eapol_test"
 
 # parse config
 
-debug "loading profiles from '$path_config/testrad.conf.sh'"
-
-. "$path_config/testrad.conf.sh" || die "could not load configuration"
+lib::find_file config= config:{,synced/}testrad.conf.sh
+if [[ $config ]]; then
+	debug "loading profiles from '$config'"
+	. "$config" || die "could not load configuration"
+fi
 
 # parse arguments
 
