upload: show an error message when rsync fails

diff --git a/net/upload b/net/upload
--- a/net/upload
+++ b/net/upload
@@ -201,7 +201,10 @@ for arg; do
 		if r:test -s "$target" && ! (( arg_clobber )); then
 			notice "'$name' already exists on server"
 		else
-			rsync -Pst "$source" "$target" >&2
+			rsync -Pst "$source" "$target" >&2 || {
+				err "upload of '$source' to '$target' failed"
+				continue
+			}
 			ks:setattr "$source" upload.path "$target"
 			ks:setattr "$source" upload.url "$url"
 		fi
