upload: always make noclobber failures fatal

diff --git a/net/upload b/net/upload
--- a/net/upload
+++ b/net/upload
@@ -199,15 +199,15 @@ for arg; do
 		fi
 	else
 		if r:test -s "$target" && ! (( arg_clobber )); then
-			notice "'$name' already exists on server"
-		else
-			rsync -Pst "$source" "$target" >&2 || {
-				err "upload of '$source' to '$target' failed"
-				continue
-			}
-			ks:setattr "$source" upload.path "$target"
-			ks:setattr "$source" upload.url "$url"
+			err "'$name' already exists on server"
+			continue
 		fi
+		if ! rsync -Pst "$source" "$target" >&2; then
+			err "upload of '$source' to '$target' failed"
+			continue
+		fi
+		ks:setattr "$source" upload.path "$target"
+		ks:setattr "$source" upload.url "$url"
 
 		echo "$name → $url"
 		clip+=("$url")
