upload: read servers from config file

diff --git a/net/upload b/net/upload
--- a/net/upload
+++ b/net/upload
@@ -30,6 +30,7 @@ r:rm_rvf() {
 	ks:sshrun "$host" rm -rvf "$path"
 }
 
+declare -- conf="$path_config/upload.conf"
 declare -A fsbase urlbase
 
 fsbase="virgule:nullroute/tmp"
@@ -40,6 +41,10 @@ urlbase[fs1]="http://fs1.nullroute.eu.org/tmp"
 
 fsbase[fs2]="ns228507:pub/fs2/tmp"
 urlbase[fs2]="http://fs2.nullroute.eu.org/tmp"
+
+if [[ -e $conf ]; then
+	. "$conf" || die "could not load configuration from '$conf'"
+fi
 
 # parse command line
 
