sx: report more errors

diff --git a/desktop/sx b/desktop/sx
--- a/desktop/sx
+++ b/desktop/sx
@@ -1,28 +1,24 @@
 #!/bin/sh
 
-if ! vt="vt$(fgconsole)"; then
-	echo "error: could not determine current VT" >&2
-	exit 1
-fi
+die() { echo "error: $*" >&2; exit 1; }
 
 # find the xinitrc script
 
 xclient=${XDG_CONFIG_HOME:-~/.config}/xinitrc
-if [ ! -e "$xclient" ]; then
-	xclient=~/.xinitrc
-fi
+[ -f "$xclient" ] || xclient=~/.xinitrc
+[ -f "$xclient" ] || die "could not find an xinitrc script"
 set -- "$xclient" "$@"
 
 # prepare general environment
 
+vt="vt$(fgconsole)" || die "could not determine current VT"
+
 exec </dev/null
 cd ~
+
 unset DBUS_SESSION_BUS_ADDRESS
 export DISPLAY=$(next-display)
-if [ ! "$DISPLAY" ]; then
-	echo "error: could not find a free display" >&2
-	exit 1
-fi
+[ "$DISPLAY" ] || die "could not find a free display"
 unset SHLVL
 export XAUTHORITY=~/.Xauthority
 
@@ -30,7 +26,8 @@ export XAUTHORITY=~/.Xauthority
 
 xauth remove "$HOSTNAME$DISPLAY"
 xauth remove "$DISPLAY"
-xauth add "$DISPLAY" MIT-MAGIC-COOKIE-1 $(mcookie)
+xauth add "$DISPLAY" MIT-MAGIC-COOKIE-1 $(mcookie) \
+	|| die "could not update $XAUTHORITY"
 
 # start Xorg
 
