sx: fail if $DISPLAY ends up empty

diff --git a/desktop/sx b/desktop/sx
--- a/desktop/sx
+++ b/desktop/sx
@@ -1,9 +1,9 @@
 #!/bin/sh
 
-vt="vt$(fgconsole)" || {
-	echo "Unable to determine current VT"
+if ! vt="vt$(fgconsole)"; then
+	echo "error: could not determine current VT"
 	exit 1
-}
+fi
 
 : ${XDG_CONFIG_HOME:=~/.config}
 if [ -e "$XDG_CONFIG_HOME/xinitrc" ]; then
@@ -14,6 +14,10 @@ fi
 
 export DISPLAY=$(next-display)
 export XAUTHORITY=~/.Xauthority
+if [ ! "$DISPLAY" ]; then
+	echo "error: could not find a free display"
+	exit 1
+fi
 
 cd ~
 xauth remove "$HOSTNAME$DISPLAY"
