sx: make sure we have XDG_RUNTIME_DIR
systeeeeemd all the way

diff --git a/desktop/sx b/desktop/sx
--- a/desktop/sx
+++ b/desktop/sx
@@ -1,14 +1,17 @@
 #!/bin/sh
 
-# bail early if not on a VC
+if ! test -O "$XDG_RUNTIME_DIR"; then
+	echo "$0: XDG_RUNTIME_DIR missing or not owned" >&2
+	exit 1
+fi
 
-vt="vt$(fgconsole)" || exit
-
-# set environment
+if ! vt="vt$(fgconsole)"; then
+	echo "$0: could not determine current virtual terminal" >&2
+	exit 1
+fi
 
 exec </dev/null
 cd ~
-
 unset DBUS_SESSION_BUS_ADDRESS
 unset SHLVL
 export DISPLAY=$(i=0;
