sx: shuffle

diff --git a/desktop/sx b/desktop/sx
--- a/desktop/sx
+++ b/desktop/sx
@@ -1,36 +1,44 @@
 #!/bin/sh
 
 if ! vt="vt$(fgconsole)"; then
-	echo "error: could not determine current VT"
+	echo "error: could not determine current VT" >&2
 	exit 1
 fi
 
-unset DBUS_SESSION_BUS_ADDRESS
-unset SHLVL
-export DISPLAY=$(next-display)
-export XAUTHORITY=~/.Xauthority
-if [ ! "$DISPLAY" ]; then
-	echo "error: could not find a free display"
-	exit 1
-fi
+# find the xinitrc script
 
-XINITRC=${XDG_CONFIG_HOME:-~/.config}/xinitrc
-if [ ! -e "$XINITRC" ]; then
-	XINITRC=~/.xinitrc
+xclient=${XDG_CONFIG_HOME:-~/.config}/xinitrc
+if [ ! -e "$xclient" ]; then
+	xclient=~/.xinitrc
 fi
+set -- "$xclient" "$@"
 
+# prepare general environment
+
+exec </dev/null
 cd ~
+unset DBUS_SESSION_BUS_ADDRESS
+export DISPLAY=$(next-display)
+if [ ! "$DISPLAY" ]; then
+	echo "error: could not find a free display" >&2
+	exit 1
+fi
+unset SHLVL
+export XAUTHORITY=~/.Xauthority
+
+# prepare Xauth
+
 xauth remove "$HOSTNAME$DISPLAY"
 xauth remove "$DISPLAY"
 xauth add "$DISPLAY" MIT-MAGIC-COOKIE-1 $(mcookie)
 
-echo "Starting Xorg on display $DISPLAY"
-xinit "$XINITRC" "$@" -- "$DISPLAY" "$vt" \
-	-noreset \
-	-auth "$XAUTHORITY" \
-	-quiet \
-	-background none \
-	< /dev/null; r=$?
+# start Xorg
+
+echo "Starting Xorg on display $DISPLAY ($vt)"
+xinit "$@" -- "$DISPLAY" "$vt" -noreset -auth "$XAUTHORITY" -quiet -background none
+r=$?
+
+# clean up Xauth
 
 xauth remove "$DISPLAY"
 exit $r
